package com.tradepass.framework.rpc.core;

// Generated by scripts/generate-domain-rpc.py from tradepass-module-identity/tradepass-module-identity-api/src/main/java/com/tradepass/module/identity/api/permission/AccessControlOperations.java.
import com.tradepass.framework.common.pojo.TradePassDtos;
import com.tradepass.framework.common.pojo.TradePassDtos.MemberRole;
import java.util.List;
import com.tradepass.module.identity.api.permission.AccessControlOperations;
import com.tradepass.module.identity.api.permission.AccessControlOperations.*;
import com.tradepass.framework.rpc.config.DomainFeignConfiguration;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.context.annotation.*;
import org.springframework.boot.autoconfigure.condition.*;
import org.springframework.web.bind.annotation.*;

@Configuration(proxyBeanMethods = false)
@ConditionalOnProperty(name = "tradepass.services.split", havingValue = "true")
@Import(AccessControlOperationsHttp.Endpoint.class)
public class AccessControlOperationsHttp {
    public record IsActiveMember2Request(long companyId, long userId) {}
    public record ResolveCompanyId1Request(String companyId) {}
    public record RequireManager1Request(long companyId) {}
    public record RequireLegal1Request(long companyId) {}
    public record RequireMemberOrClaim1Request(long companyId) {}
    public record RequireCompanyProfileAccess1Request(long targetCompanyId) {}
    public record RequireLegalOrClaim1Request(long companyId) {}
    public record RequireCertificationOperator1Request(long companyId) {}
    public record RequirePermission2Request(long companyId, String permission) {}
    public record RequireAnyPermission2Request(long companyId, String[] permissions) {}
    public record HasPermission2Request(long companyId, String permission) {}
    public record EffectiveRole2Request(long companyId, long userId) {}

    @FeignClient(name = "tradepass-identity", contextId = "AccessControlOperationsHttp",
            url = "${tradepass.services.identity-url:}", configuration = DomainFeignConfiguration.class)
    public interface Client {
        @PostMapping("/internal/domain/AccessControlOperations/isActiveMember2")
        boolean isActiveMember2(@RequestBody IsActiveMember2Request request);
        @PostMapping("/internal/domain/AccessControlOperations/resolveCompanyId1")
        Long resolveCompanyId1(@RequestBody ResolveCompanyId1Request request);
        @PostMapping("/internal/domain/AccessControlOperations/requireManager1")
        void requireManager1(@RequestBody RequireManager1Request request);
        @PostMapping("/internal/domain/AccessControlOperations/requireLegal1")
        void requireLegal1(@RequestBody RequireLegal1Request request);
        @PostMapping("/internal/domain/AccessControlOperations/requireMemberOrClaim1")
        void requireMemberOrClaim1(@RequestBody RequireMemberOrClaim1Request request);
        @PostMapping("/internal/domain/AccessControlOperations/requireCompanyProfileAccess1")
        CompanyProfileAccess requireCompanyProfileAccess1(@RequestBody RequireCompanyProfileAccess1Request request);
        @PostMapping("/internal/domain/AccessControlOperations/requireLegalOrClaim1")
        void requireLegalOrClaim1(@RequestBody RequireLegalOrClaim1Request request);
        @PostMapping("/internal/domain/AccessControlOperations/requireCertificationOperator1")
        void requireCertificationOperator1(@RequestBody RequireCertificationOperator1Request request);
        @PostMapping("/internal/domain/AccessControlOperations/requirePermission2")
        void requirePermission2(@RequestBody RequirePermission2Request request);
        @PostMapping("/internal/domain/AccessControlOperations/requireAnyPermission2")
        void requireAnyPermission2(@RequestBody RequireAnyPermission2Request request);
        @PostMapping("/internal/domain/AccessControlOperations/hasPermission2")
        boolean hasPermission2(@RequestBody HasPermission2Request request);
        @PostMapping("/internal/domain/AccessControlOperations/effectiveRole2")
        EffectiveRole effectiveRole2(@RequestBody EffectiveRole2Request request);
    }

    @Bean
    @ConditionalOnExpression("'${tradepass.runtime.role:}' != 'identity'")
    AccessControlOperations remoteAccessControlOperations(Client client) {
        return new AccessControlOperations() {
            @Override public boolean isActiveMember(long companyId, long userId) { return client.isActiveMember2(new IsActiveMember2Request(companyId, userId)); }
            @Override public Long resolveCompanyId(String companyId) { return client.resolveCompanyId1(new ResolveCompanyId1Request(companyId)); }
            @Override public void requireManager(long companyId) { client.requireManager1(new RequireManager1Request(companyId)); }
            @Override public void requireLegal(long companyId) { client.requireLegal1(new RequireLegal1Request(companyId)); }
            @Override public void requireMemberOrClaim(long companyId) { client.requireMemberOrClaim1(new RequireMemberOrClaim1Request(companyId)); }
            @Override public CompanyProfileAccess requireCompanyProfileAccess(long targetCompanyId) { return client.requireCompanyProfileAccess1(new RequireCompanyProfileAccess1Request(targetCompanyId)); }
            @Override public void requireLegalOrClaim(long companyId) { client.requireLegalOrClaim1(new RequireLegalOrClaim1Request(companyId)); }
            @Override public void requireCertificationOperator(long companyId) { client.requireCertificationOperator1(new RequireCertificationOperator1Request(companyId)); }
            @Override public void requirePermission(long companyId, String permission) { client.requirePermission2(new RequirePermission2Request(companyId, permission)); }
            @Override public void requireAnyPermission(long companyId, String... permissions) { client.requireAnyPermission2(new RequireAnyPermission2Request(companyId, permissions)); }
            @Override public boolean hasPermission(long companyId, String permission) { return client.hasPermission2(new HasPermission2Request(companyId, permission)); }
            @Override public EffectiveRole effectiveRole(long companyId, long userId) { return client.effectiveRole2(new EffectiveRole2Request(companyId, userId)); }
        };
    }

    @RestController
    @ConditionalOnProperty(name = "tradepass.runtime.role", havingValue = "identity")
    public static class Endpoint {
        private final AccessControlOperations operations;
        public Endpoint(AccessControlOperations operations) { this.operations = operations; }
        @PostMapping("/internal/domain/AccessControlOperations/isActiveMember2")
        public boolean isActiveMember2(@RequestBody IsActiveMember2Request request) { return operations.isActiveMember(request.companyId(), request.userId()); }
        @PostMapping("/internal/domain/AccessControlOperations/resolveCompanyId1")
        public Long resolveCompanyId1(@RequestBody ResolveCompanyId1Request request) { return operations.resolveCompanyId(request.companyId()); }
        @PostMapping("/internal/domain/AccessControlOperations/requireManager1")
        public void requireManager1(@RequestBody RequireManager1Request request) { operations.requireManager(request.companyId()); }
        @PostMapping("/internal/domain/AccessControlOperations/requireLegal1")
        public void requireLegal1(@RequestBody RequireLegal1Request request) { operations.requireLegal(request.companyId()); }
        @PostMapping("/internal/domain/AccessControlOperations/requireMemberOrClaim1")
        public void requireMemberOrClaim1(@RequestBody RequireMemberOrClaim1Request request) { operations.requireMemberOrClaim(request.companyId()); }
        @PostMapping("/internal/domain/AccessControlOperations/requireCompanyProfileAccess1")
        public CompanyProfileAccess requireCompanyProfileAccess1(@RequestBody RequireCompanyProfileAccess1Request request) { return operations.requireCompanyProfileAccess(request.targetCompanyId()); }
        @PostMapping("/internal/domain/AccessControlOperations/requireLegalOrClaim1")
        public void requireLegalOrClaim1(@RequestBody RequireLegalOrClaim1Request request) { operations.requireLegalOrClaim(request.companyId()); }
        @PostMapping("/internal/domain/AccessControlOperations/requireCertificationOperator1")
        public void requireCertificationOperator1(@RequestBody RequireCertificationOperator1Request request) { operations.requireCertificationOperator(request.companyId()); }
        @PostMapping("/internal/domain/AccessControlOperations/requirePermission2")
        public void requirePermission2(@RequestBody RequirePermission2Request request) { operations.requirePermission(request.companyId(), request.permission()); }
        @PostMapping("/internal/domain/AccessControlOperations/requireAnyPermission2")
        public void requireAnyPermission2(@RequestBody RequireAnyPermission2Request request) { operations.requireAnyPermission(request.companyId(), request.permissions()); }
        @PostMapping("/internal/domain/AccessControlOperations/hasPermission2")
        public boolean hasPermission2(@RequestBody HasPermission2Request request) { return operations.hasPermission(request.companyId(), request.permission()); }
        @PostMapping("/internal/domain/AccessControlOperations/effectiveRole2")
        public EffectiveRole effectiveRole2(@RequestBody EffectiveRole2Request request) { return operations.effectiveRole(request.companyId(), request.userId()); }
    }
}
