package com.tradepass.framework.rpc.core;

// Generated by scripts/generate-domain-rpc.py from tradepass-module-trade/tradepass-module-trade-api/src/main/java/com/tradepass/module/trade/api/approval/ApprovalOperations.java.
import java.util.List;
import java.util.Map;
import com.tradepass.module.trade.api.approval.ApprovalOperations;
import com.tradepass.module.trade.api.approval.ApprovalOperations.*;
import com.tradepass.framework.rpc.config.DomainFeignConfiguration;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.context.annotation.*;
import org.springframework.boot.autoconfigure.condition.*;
import org.springframework.web.bind.annotation.*;

@Configuration(proxyBeanMethods = false)
@ConditionalOnProperty(name = "tradepass.services.split", havingValue = "true")
@Import(ApprovalOperationsHttp.Endpoint.class)
public class ApprovalOperationsHttp {
    public record PendingFulfillment0Request() {}
    public record Results0Request() {}
    public record Summary0Request() {}
    public record MarkResultRead1Request(Long id) {}
    public record RecordResult9Request(long recipientCompanyId, long sourceCompanyId, String resultType, long sourceId, Long contractId, String resultStatus, String title, String detail, String rejectedReason) {}

    @FeignClient(name = "${tradepass.services.trade-name:tradepass-trade}", contextId = "ApprovalOperationsHttp",
            url = "${tradepass.services.trade-url:}", configuration = DomainFeignConfiguration.class)
    public interface Client {
        @PostMapping("/internal/domain/ApprovalOperations/pendingFulfillment0")
        List<Map<String, Object>> pendingFulfillment0(@RequestBody PendingFulfillment0Request request);
        @PostMapping("/internal/domain/ApprovalOperations/results0")
        List<Map<String, Object>> results0(@RequestBody Results0Request request);
        @PostMapping("/internal/domain/ApprovalOperations/summary0")
        Map<String, Object> summary0(@RequestBody Summary0Request request);
        @PostMapping("/internal/domain/ApprovalOperations/markResultRead1")
        void markResultRead1(@RequestBody MarkResultRead1Request request);
        @PostMapping("/internal/domain/ApprovalOperations/recordResult9")
        void recordResult9(@RequestBody RecordResult9Request request);
    }

    @Bean
    @ConditionalOnExpression("!T(com.tradepass.framework.common.core.HostedRoles).hosts('${tradepass.runtime.role:}', 'trade')")
    ApprovalOperations remoteApprovalOperations(Client client) {
        return new ApprovalOperations() {
            @Override public List<Map<String, Object>> pendingFulfillment() { return client.pendingFulfillment0(new PendingFulfillment0Request()); }
            @Override public List<Map<String, Object>> results() { return client.results0(new Results0Request()); }
            @Override public Map<String, Object> summary() { return client.summary0(new Summary0Request()); }
            @Override public void markResultRead(Long id) { client.markResultRead1(new MarkResultRead1Request(id)); }
            @Override public void recordResult(long recipientCompanyId, long sourceCompanyId, String resultType, long sourceId, Long contractId, String resultStatus, String title, String detail, String rejectedReason) { client.recordResult9(new RecordResult9Request(recipientCompanyId, sourceCompanyId, resultType, sourceId, contractId, resultStatus, title, detail, rejectedReason)); }
        };
    }

    @RestController
    @ConditionalOnExpression("T(com.tradepass.framework.common.core.HostedRoles).hosts('${tradepass.runtime.role:}', 'trade')")
    public static class Endpoint {
        private final ApprovalOperations operations;
        public Endpoint(ApprovalOperations operations) { this.operations = operations; }
        @PostMapping("/internal/domain/ApprovalOperations/pendingFulfillment0")
        public List<Map<String, Object>> pendingFulfillment0(@RequestBody PendingFulfillment0Request request) { return operations.pendingFulfillment(); }
        @PostMapping("/internal/domain/ApprovalOperations/results0")
        public List<Map<String, Object>> results0(@RequestBody Results0Request request) { return operations.results(); }
        @PostMapping("/internal/domain/ApprovalOperations/summary0")
        public Map<String, Object> summary0(@RequestBody Summary0Request request) { return operations.summary(); }
        @PostMapping("/internal/domain/ApprovalOperations/markResultRead1")
        public void markResultRead1(@RequestBody MarkResultRead1Request request) { operations.markResultRead(request.id()); }
        @PostMapping("/internal/domain/ApprovalOperations/recordResult9")
        public void recordResult9(@RequestBody RecordResult9Request request) { operations.recordResult(request.recipientCompanyId(), request.sourceCompanyId(), request.resultType(), request.sourceId(), request.contractId(), request.resultStatus(), request.title(), request.detail(), request.rejectedReason()); }
    }
}
