package com.tradepass.framework.rpc.core;

// Generated by scripts/generate-domain-rpc.py from tradepass-module-settlement/tradepass-module-settlement-api/src/main/java/com/tradepass/module/settlement/api/attachment/AttachmentStateOperations.java.

import com.tradepass.module.settlement.api.attachment.AttachmentStateOperations;
import com.tradepass.module.settlement.api.attachment.AttachmentStateOperations.*;
import com.tradepass.framework.rpc.config.DomainFeignConfiguration;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.context.annotation.*;
import org.springframework.boot.autoconfigure.condition.*;
import org.springframework.web.bind.annotation.*;

@Configuration(proxyBeanMethods = false)
@ConditionalOnProperty(name = "tradepass.services.split", havingValue = "true")
@Import(AttachmentStateOperationsHttp.Endpoint.class)
public class AttachmentStateOperationsHttp {
    public record State2Request(Long id, boolean includeDeleted) {}
    public record EffectiveCount1Request(Long contractId) {}
    public record UnfinishedCount1Request(Long contractId) {}
    public record VoidApproved1Request(Long id) {}
    public record PendingConfirmationCount1Request(long companyId) {}

    @FeignClient(name = "${tradepass.services.settlement-name:tradepass-settlement}", contextId = "AttachmentStateOperationsHttp",
            url = "${tradepass.services.settlement-url:}", configuration = DomainFeignConfiguration.class)
    public interface Client {
        @PostMapping("/internal/domain/AttachmentStateOperations/state2")
        AttachmentState state2(@RequestBody State2Request request);
        @PostMapping("/internal/domain/AttachmentStateOperations/effectiveCount1")
        long effectiveCount1(@RequestBody EffectiveCount1Request request);
        @PostMapping("/internal/domain/AttachmentStateOperations/unfinishedCount1")
        long unfinishedCount1(@RequestBody UnfinishedCount1Request request);
        @PostMapping("/internal/domain/AttachmentStateOperations/voidApproved1")
        int voidApproved1(@RequestBody VoidApproved1Request request);
        @PostMapping("/internal/domain/AttachmentStateOperations/pendingConfirmationCount1")
        long pendingConfirmationCount1(@RequestBody PendingConfirmationCount1Request request);
    }

    @Bean
    @ConditionalOnExpression("!T(com.tradepass.framework.common.core.HostedRoles).hosts('${tradepass.runtime.role:}', 'settlement')")
    AttachmentStateOperations remoteAttachmentStateOperations(Client client) {
        return new AttachmentStateOperations() {
            @Override public AttachmentState state(Long id, boolean includeDeleted) { return client.state2(new State2Request(id, includeDeleted)); }
            @Override public long effectiveCount(Long contractId) { return client.effectiveCount1(new EffectiveCount1Request(contractId)); }
            @Override public long unfinishedCount(Long contractId) { return client.unfinishedCount1(new UnfinishedCount1Request(contractId)); }
            @Override public int voidApproved(Long id) { return client.voidApproved1(new VoidApproved1Request(id)); }
            @Override public long pendingConfirmationCount(long companyId) { return client.pendingConfirmationCount1(new PendingConfirmationCount1Request(companyId)); }
        };
    }

    @RestController
    @ConditionalOnExpression("T(com.tradepass.framework.common.core.HostedRoles).hosts('${tradepass.runtime.role:}', 'settlement')")
    public static class Endpoint {
        private final AttachmentStateOperations operations;
        public Endpoint(AttachmentStateOperations operations) { this.operations = operations; }
        @PostMapping("/internal/domain/AttachmentStateOperations/state2")
        public AttachmentState state2(@RequestBody State2Request request) { return operations.state(request.id(), request.includeDeleted()); }
        @PostMapping("/internal/domain/AttachmentStateOperations/effectiveCount1")
        public long effectiveCount1(@RequestBody EffectiveCount1Request request) { return operations.effectiveCount(request.contractId()); }
        @PostMapping("/internal/domain/AttachmentStateOperations/unfinishedCount1")
        public long unfinishedCount1(@RequestBody UnfinishedCount1Request request) { return operations.unfinishedCount(request.contractId()); }
        @PostMapping("/internal/domain/AttachmentStateOperations/voidApproved1")
        public int voidApproved1(@RequestBody VoidApproved1Request request) { return operations.voidApproved(request.id()); }
        @PostMapping("/internal/domain/AttachmentStateOperations/pendingConfirmationCount1")
        public long pendingConfirmationCount1(@RequestBody PendingConfirmationCount1Request request) { return operations.pendingConfirmationCount(request.companyId()); }
    }
}
