package com.tradepass.framework.rpc.core;

// Generated by scripts/generate-domain-rpc.py from tradepass-module-settlement/tradepass-module-settlement-api/src/main/java/com/tradepass/module/settlement/api/attachment/AttachmentApprovalOperations.java.
import java.util.List;
import java.util.Map;
import java.time.LocalDateTime;
import com.tradepass.module.settlement.api.attachment.AttachmentApprovalOperations;
import com.tradepass.module.settlement.api.attachment.AttachmentApprovalOperations.*;
import com.tradepass.framework.rpc.config.DomainFeignConfiguration;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.context.annotation.*;
import org.springframework.boot.autoconfigure.condition.*;
import org.springframework.web.bind.annotation.*;

@Configuration(proxyBeanMethods = false)
@ConditionalOnProperty(name = "tradepass.services.split", havingValue = "true")
@Import(AttachmentApprovalOperationsHttp.Endpoint.class)
public class AttachmentApprovalOperationsHttp {
    public record PendingAttachments1Request(long companyId) {}

    @FeignClient(name = "${tradepass.services.settlement-name:tradepass-settlement}", contextId = "AttachmentApprovalOperationsHttp",
            url = "${tradepass.services.settlement-url:}", configuration = DomainFeignConfiguration.class)
    public interface Client {
        @PostMapping("/internal/domain/AttachmentApprovalOperations/pendingAttachments1")
        List<PendingAttachment> pendingAttachments1(@RequestBody PendingAttachments1Request request);
    }

    @Bean
    @ConditionalOnExpression("!T(com.tradepass.framework.common.core.HostedRoles).hosts('${tradepass.runtime.role:}', 'settlement')")
    AttachmentApprovalOperations remoteAttachmentApprovalOperations(Client client) {
        return new AttachmentApprovalOperations() {
            @Override public List<PendingAttachment> pendingAttachments(long companyId) { return client.pendingAttachments1(new PendingAttachments1Request(companyId)); }
        };
    }

    @RestController
    @ConditionalOnExpression("T(com.tradepass.framework.common.core.HostedRoles).hosts('${tradepass.runtime.role:}', 'settlement')")
    public static class Endpoint {
        private final AttachmentApprovalOperations operations;
        public Endpoint(AttachmentApprovalOperations operations) { this.operations = operations; }
        @PostMapping("/internal/domain/AttachmentApprovalOperations/pendingAttachments1")
        public List<PendingAttachment> pendingAttachments1(@RequestBody PendingAttachments1Request request) { return operations.pendingAttachments(request.companyId()); }
    }
}
