package com.tradepass.framework.rpc.core;

// Generated by scripts/generate-domain-rpc.py from tradepass-module-trade/tradepass-module-trade-api/src/main/java/com/tradepass/module/trade/api/bilateral/BilateralActionOperations.java.
import com.tradepass.module.contract.api.contract.dto.TradeContractRespDTO;
import java.util.Map;
import com.tradepass.module.trade.api.bilateral.BilateralActionOperations;
import com.tradepass.module.trade.api.bilateral.BilateralActionOperations.*;
import com.tradepass.framework.rpc.config.DomainFeignConfiguration;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.context.annotation.*;
import org.springframework.boot.autoconfigure.condition.*;
import org.springframework.web.bind.annotation.*;

@Configuration(proxyBeanMethods = false)
@ConditionalOnProperty(name = "tradepass.services.split", havingValue = "true")
@Import(BilateralActionOperationsHttp.Endpoint.class)
public class BilateralActionOperationsHttp {
    public record Request5Request(String bizType, Long bizId, String actionType, String reason, boolean riskConfirmed) {}
    public record Decide3Request(Long id, String decision, String reason) {}
    public record Cancel1Request(Long id) {}
    public record Active2Request(String bizType, Long bizId) {}
    public record State3Request(long companyId, String bizType, Long bizId) {}
    public record RequireContractMutable1Request(TradeContractRespDTO contract) {}
    public record IsContractReadOnly1Request(TradeContractRespDTO contract) {}

    @FeignClient(name = "${tradepass.services.trade-name:tradepass-trade}", contextId = "BilateralActionOperationsHttp",
            url = "${tradepass.services.trade-url:}", configuration = DomainFeignConfiguration.class)
    public interface Client {
        @PostMapping("/internal/domain/BilateralActionOperations/request5")
        Map<String, Object> request5(@RequestBody Request5Request request);
        @PostMapping("/internal/domain/BilateralActionOperations/decide3")
        Map<String, Object> decide3(@RequestBody Decide3Request request);
        @PostMapping("/internal/domain/BilateralActionOperations/cancel1")
        String cancel1(@RequestBody Cancel1Request request);
        @PostMapping("/internal/domain/BilateralActionOperations/active2")
        Map<String, Object> active2(@RequestBody Active2Request request);
        @PostMapping("/internal/domain/BilateralActionOperations/state3")
        ActionState state3(@RequestBody State3Request request);
        @PostMapping("/internal/domain/BilateralActionOperations/requireContractMutable1")
        void requireContractMutable1(@RequestBody RequireContractMutable1Request request);
        @PostMapping("/internal/domain/BilateralActionOperations/isContractReadOnly1")
        boolean isContractReadOnly1(@RequestBody IsContractReadOnly1Request request);
    }

    @Bean
    @ConditionalOnExpression("!T(com.tradepass.framework.common.core.HostedRoles).hosts('${tradepass.runtime.role:}', 'trade')")
    BilateralActionOperations remoteBilateralActionOperations(Client client) {
        return new BilateralActionOperations() {
            @Override public Map<String, Object> request(String bizType, Long bizId, String actionType, String reason, boolean riskConfirmed) { return client.request5(new Request5Request(bizType, bizId, actionType, reason, riskConfirmed)); }
            @Override public Map<String, Object> decide(Long id, String decision, String reason) { return client.decide3(new Decide3Request(id, decision, reason)); }
            @Override public String cancel(Long id) { return client.cancel1(new Cancel1Request(id)); }
            @Override public Map<String, Object> active(String bizType, Long bizId) { return client.active2(new Active2Request(bizType, bizId)); }
            @Override public ActionState state(long companyId, String bizType, Long bizId) { return client.state3(new State3Request(companyId, bizType, bizId)); }
            @Override public void requireContractMutable(TradeContractRespDTO contract) { client.requireContractMutable1(new RequireContractMutable1Request(contract)); }
            @Override public boolean isContractReadOnly(TradeContractRespDTO contract) { return client.isContractReadOnly1(new IsContractReadOnly1Request(contract)); }
        };
    }

    @RestController
    @ConditionalOnExpression("T(com.tradepass.framework.common.core.HostedRoles).hosts('${tradepass.runtime.role:}', 'trade')")
    public static class Endpoint {
        private final BilateralActionOperations operations;
        public Endpoint(BilateralActionOperations operations) { this.operations = operations; }
        @PostMapping("/internal/domain/BilateralActionOperations/request5")
        public Map<String, Object> request5(@RequestBody Request5Request request) { return operations.request(request.bizType(), request.bizId(), request.actionType(), request.reason(), request.riskConfirmed()); }
        @PostMapping("/internal/domain/BilateralActionOperations/decide3")
        public Map<String, Object> decide3(@RequestBody Decide3Request request) { return operations.decide(request.id(), request.decision(), request.reason()); }
        @PostMapping("/internal/domain/BilateralActionOperations/cancel1")
        public String cancel1(@RequestBody Cancel1Request request) { return operations.cancel(request.id()); }
        @PostMapping("/internal/domain/BilateralActionOperations/active2")
        public Map<String, Object> active2(@RequestBody Active2Request request) { return operations.active(request.bizType(), request.bizId()); }
        @PostMapping("/internal/domain/BilateralActionOperations/state3")
        public ActionState state3(@RequestBody State3Request request) { return operations.state(request.companyId(), request.bizType(), request.bizId()); }
        @PostMapping("/internal/domain/BilateralActionOperations/requireContractMutable1")
        public void requireContractMutable1(@RequestBody RequireContractMutable1Request request) { operations.requireContractMutable(request.contract()); }
        @PostMapping("/internal/domain/BilateralActionOperations/isContractReadOnly1")
        public boolean isContractReadOnly1(@RequestBody IsContractReadOnly1Request request) { return operations.isContractReadOnly(request.contract()); }
    }
}
