package com.tradepass.framework.rpc.core;

// Generated by scripts/generate-domain-rpc.py from tradepass-module-trade/tradepass-module-trade-api/src/main/java/com/tradepass/module/trade/api/bilateral/BilateralStateOperations.java.
import java.util.List;
import com.tradepass.module.trade.api.bilateral.BilateralStateOperations;
import com.tradepass.module.trade.api.bilateral.BilateralStateOperations.*;
import com.tradepass.framework.rpc.config.DomainFeignConfiguration;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.context.annotation.*;
import org.springframework.boot.autoconfigure.condition.*;
import org.springframework.web.bind.annotation.*;

@Configuration(proxyBeanMethods = false)
@ConditionalOnProperty(name = "tradepass.services.split", havingValue = "true")
@Import(BilateralStateOperationsHttp.Endpoint.class)
public class BilateralStateOperationsHttp {
    public record ApprovedVoids2Request(Long contractId, boolean lock) {}
    public record PendingResumes3Request(Long contractId, boolean contractOnly, boolean lock) {}
    public record CancelApprovedVoids1Request(Long contractId) {}

    @FeignClient(name = "tradepass-trade", contextId = "BilateralStateOperationsHttp",
            url = "${tradepass.services.trade-url:}", configuration = DomainFeignConfiguration.class)
    public interface Client {
        @PostMapping("/internal/domain/BilateralStateOperations/approvedVoids2")
        List<Long> approvedVoids2(@RequestBody ApprovedVoids2Request request);
        @PostMapping("/internal/domain/BilateralStateOperations/pendingResumes3")
        List<Long> pendingResumes3(@RequestBody PendingResumes3Request request);
        @PostMapping("/internal/domain/BilateralStateOperations/cancelApprovedVoids1")
        int cancelApprovedVoids1(@RequestBody CancelApprovedVoids1Request request);
    }

    @Bean
    @ConditionalOnExpression("'${tradepass.runtime.role:}' != 'trade'")
    BilateralStateOperations remoteBilateralStateOperations(Client client) {
        return new BilateralStateOperations() {
            @Override public List<Long> approvedVoids(Long contractId, boolean lock) { return client.approvedVoids2(new ApprovedVoids2Request(contractId, lock)); }
            @Override public List<Long> pendingResumes(Long contractId, boolean contractOnly, boolean lock) { return client.pendingResumes3(new PendingResumes3Request(contractId, contractOnly, lock)); }
            @Override public int cancelApprovedVoids(Long contractId) { return client.cancelApprovedVoids1(new CancelApprovedVoids1Request(contractId)); }
        };
    }

    @RestController
    @ConditionalOnProperty(name = "tradepass.runtime.role", havingValue = "trade")
    public static class Endpoint {
        private final BilateralStateOperations operations;
        public Endpoint(BilateralStateOperations operations) { this.operations = operations; }
        @PostMapping("/internal/domain/BilateralStateOperations/approvedVoids2")
        public List<Long> approvedVoids2(@RequestBody ApprovedVoids2Request request) { return operations.approvedVoids(request.contractId(), request.lock()); }
        @PostMapping("/internal/domain/BilateralStateOperations/pendingResumes3")
        public List<Long> pendingResumes3(@RequestBody PendingResumes3Request request) { return operations.pendingResumes(request.contractId(), request.contractOnly(), request.lock()); }
        @PostMapping("/internal/domain/BilateralStateOperations/cancelApprovedVoids1")
        public int cancelApprovedVoids1(@RequestBody CancelApprovedVoids1Request request) { return operations.cancelApprovedVoids(request.contractId()); }
    }
}
