package com.tradepass.framework.rpc.core;

// Generated by scripts/generate-domain-rpc.py from tradepass-module-trade/tradepass-module-trade-api/src/main/java/com/tradepass/module/trade/api/document/BusinessDocumentOperations.java.
import com.tradepass.module.trade.api.document.dto.BusinessDocumentRespDTO;
import java.util.List;
import java.util.Map;
import com.tradepass.module.trade.api.document.BusinessDocumentOperations;
import com.tradepass.module.trade.api.document.BusinessDocumentOperations.*;
import com.tradepass.framework.rpc.config.DomainFeignConfiguration;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.context.annotation.*;
import org.springframework.boot.autoconfigure.condition.*;
import org.springframework.web.bind.annotation.*;

@Configuration(proxyBeanMethods = false)
@ConditionalOnProperty(name = "tradepass.services.split", havingValue = "true")
@Import(BusinessDocumentOperationsHttp.Endpoint.class)
public class BusinessDocumentOperationsHttp {
    public record ListTemplates1Request(String type) {}
    public record CreateTemplate1Request(Map<String, Object> body) {}
    public record DeleteTemplate1Request(Long id) {}
    public record ListDocuments2Request(Long contractId, String type) {}
    public record CreateDocument2Request(Long contractId, Map<String, Object> body) {}
    public record UpdateDraft2Request(Long id, Map<String, Object> body) {}
    public record PublishDraft1Request(Long id) {}
    public record PublishDraft2Request(Long id, Long warehouseId) {}
    public record GetDocument1Request(Long id) {}
    public record DeleteDraft1Request(Long id) {}
    public record Withdraw1Request(Long id) {}
    public record TypeLabel1Request(String type) {}
    public record DefaultTemplateContent1Request(String type) {}

    @FeignClient(name = "${tradepass.services.trade-name:tradepass-trade}", contextId = "BusinessDocumentOperationsHttp",
            url = "${tradepass.services.trade-url:}", configuration = DomainFeignConfiguration.class)
    public interface Client {
        @PostMapping("/internal/domain/BusinessDocumentOperations/listTemplates1")
        List<Map<String, Object>> listTemplates1(@RequestBody ListTemplates1Request request);
        @PostMapping("/internal/domain/BusinessDocumentOperations/createTemplate1")
        Map<String, Object> createTemplate1(@RequestBody CreateTemplate1Request request);
        @PostMapping("/internal/domain/BusinessDocumentOperations/deleteTemplate1")
        String deleteTemplate1(@RequestBody DeleteTemplate1Request request);
        @PostMapping("/internal/domain/BusinessDocumentOperations/listDocuments2")
        List<Map<String, Object>> listDocuments2(@RequestBody ListDocuments2Request request);
        @PostMapping("/internal/domain/BusinessDocumentOperations/createDocument2")
        Map<String, Object> createDocument2(@RequestBody CreateDocument2Request request);
        @PostMapping("/internal/domain/BusinessDocumentOperations/updateDraft2")
        Map<String, Object> updateDraft2(@RequestBody UpdateDraft2Request request);
        @PostMapping("/internal/domain/BusinessDocumentOperations/publishDraft1")
        Map<String, Object> publishDraft1(@RequestBody PublishDraft1Request request);
        @PostMapping("/internal/domain/BusinessDocumentOperations/publishDraft2")
        Map<String, Object> publishDraft2(@RequestBody PublishDraft2Request request);
        @PostMapping("/internal/domain/BusinessDocumentOperations/getDocument1")
        BusinessDocumentRespDTO getDocument1(@RequestBody GetDocument1Request request);
        @PostMapping("/internal/domain/BusinessDocumentOperations/deleteDraft1")
        String deleteDraft1(@RequestBody DeleteDraft1Request request);
        @PostMapping("/internal/domain/BusinessDocumentOperations/withdraw1")
        String withdraw1(@RequestBody Withdraw1Request request);
        @PostMapping("/internal/domain/BusinessDocumentOperations/typeLabel1")
        String typeLabel1(@RequestBody TypeLabel1Request request);
        @PostMapping("/internal/domain/BusinessDocumentOperations/defaultTemplateContent1")
        String defaultTemplateContent1(@RequestBody DefaultTemplateContent1Request request);
    }

    @Bean
    @ConditionalOnExpression("!T(com.tradepass.framework.common.core.HostedRoles).hosts('${tradepass.runtime.role:}', 'trade')")
    BusinessDocumentOperations remoteBusinessDocumentOperations(Client client) {
        return new BusinessDocumentOperations() {
            @Override public List<Map<String, Object>> listTemplates(String type) { return client.listTemplates1(new ListTemplates1Request(type)); }
            @Override public Map<String, Object> createTemplate(Map<String, Object> body) { return client.createTemplate1(new CreateTemplate1Request(body)); }
            @Override public String deleteTemplate(Long id) { return client.deleteTemplate1(new DeleteTemplate1Request(id)); }
            @Override public List<Map<String, Object>> listDocuments(Long contractId, String type) { return client.listDocuments2(new ListDocuments2Request(contractId, type)); }
            @Override public Map<String, Object> createDocument(Long contractId, Map<String, Object> body) { return client.createDocument2(new CreateDocument2Request(contractId, body)); }
            @Override public Map<String, Object> updateDraft(Long id, Map<String, Object> body) { return client.updateDraft2(new UpdateDraft2Request(id, body)); }
            @Override public Map<String, Object> publishDraft(Long id) { return client.publishDraft1(new PublishDraft1Request(id)); }
            @Override public Map<String, Object> publishDraft(Long id, Long warehouseId) { return client.publishDraft2(new PublishDraft2Request(id, warehouseId)); }
            @Override public BusinessDocumentRespDTO getDocument(Long id) { return client.getDocument1(new GetDocument1Request(id)); }
            @Override public String deleteDraft(Long id) { return client.deleteDraft1(new DeleteDraft1Request(id)); }
            @Override public String withdraw(Long id) { return client.withdraw1(new Withdraw1Request(id)); }
            @Override public String typeLabel(String type) { return client.typeLabel1(new TypeLabel1Request(type)); }
            @Override public String defaultTemplateContent(String type) { return client.defaultTemplateContent1(new DefaultTemplateContent1Request(type)); }
        };
    }

    @RestController
    @ConditionalOnExpression("T(com.tradepass.framework.common.core.HostedRoles).hosts('${tradepass.runtime.role:}', 'trade')")
    public static class Endpoint {
        private final BusinessDocumentOperations operations;
        public Endpoint(BusinessDocumentOperations operations) { this.operations = operations; }
        @PostMapping("/internal/domain/BusinessDocumentOperations/listTemplates1")
        public List<Map<String, Object>> listTemplates1(@RequestBody ListTemplates1Request request) { return operations.listTemplates(request.type()); }
        @PostMapping("/internal/domain/BusinessDocumentOperations/createTemplate1")
        public Map<String, Object> createTemplate1(@RequestBody CreateTemplate1Request request) { return operations.createTemplate(request.body()); }
        @PostMapping("/internal/domain/BusinessDocumentOperations/deleteTemplate1")
        public String deleteTemplate1(@RequestBody DeleteTemplate1Request request) { return operations.deleteTemplate(request.id()); }
        @PostMapping("/internal/domain/BusinessDocumentOperations/listDocuments2")
        public List<Map<String, Object>> listDocuments2(@RequestBody ListDocuments2Request request) { return operations.listDocuments(request.contractId(), request.type()); }
        @PostMapping("/internal/domain/BusinessDocumentOperations/createDocument2")
        public Map<String, Object> createDocument2(@RequestBody CreateDocument2Request request) { return operations.createDocument(request.contractId(), request.body()); }
        @PostMapping("/internal/domain/BusinessDocumentOperations/updateDraft2")
        public Map<String, Object> updateDraft2(@RequestBody UpdateDraft2Request request) { return operations.updateDraft(request.id(), request.body()); }
        @PostMapping("/internal/domain/BusinessDocumentOperations/publishDraft1")
        public Map<String, Object> publishDraft1(@RequestBody PublishDraft1Request request) { return operations.publishDraft(request.id()); }
        @PostMapping("/internal/domain/BusinessDocumentOperations/publishDraft2")
        public Map<String, Object> publishDraft2(@RequestBody PublishDraft2Request request) { return operations.publishDraft(request.id(), request.warehouseId()); }
        @PostMapping("/internal/domain/BusinessDocumentOperations/getDocument1")
        public BusinessDocumentRespDTO getDocument1(@RequestBody GetDocument1Request request) { return operations.getDocument(request.id()); }
        @PostMapping("/internal/domain/BusinessDocumentOperations/deleteDraft1")
        public String deleteDraft1(@RequestBody DeleteDraft1Request request) { return operations.deleteDraft(request.id()); }
        @PostMapping("/internal/domain/BusinessDocumentOperations/withdraw1")
        public String withdraw1(@RequestBody Withdraw1Request request) { return operations.withdraw(request.id()); }
        @PostMapping("/internal/domain/BusinessDocumentOperations/typeLabel1")
        public String typeLabel1(@RequestBody TypeLabel1Request request) { return operations.typeLabel(request.type()); }
        @PostMapping("/internal/domain/BusinessDocumentOperations/defaultTemplateContent1")
        public String defaultTemplateContent1(@RequestBody DefaultTemplateContent1Request request) { return operations.defaultTemplateContent(request.type()); }
    }
}
