package com.tradepass.framework.rpc.core;

// Generated by scripts/generate-domain-rpc.py from tradepass-module-identity/tradepass-module-identity-api/src/main/java/com/tradepass/module/identity/api/company/CompanyReader.java.
import com.tradepass.module.identity.api.company.dto.CompanyRespDTO;
import java.io.Serializable;
import com.tradepass.module.identity.api.company.CompanyReader;
import com.tradepass.module.identity.api.company.CompanyReader.*;
import com.tradepass.framework.rpc.config.DomainFeignConfiguration;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.context.annotation.*;
import org.springframework.boot.autoconfigure.condition.*;
import org.springframework.web.bind.annotation.*;

@Configuration(proxyBeanMethods = false)
@ConditionalOnProperty(name = "tradepass.services.split", havingValue = "true")
@Import(CompanyReaderHttp.Endpoint.class)
public class CompanyReaderHttp {
    public record SelectById1Request(Serializable id) {}

    @FeignClient(name = "tradepass-identity", contextId = "CompanyReaderHttp",
            url = "${tradepass.services.identity-url:}", configuration = DomainFeignConfiguration.class)
    public interface Client {
        @PostMapping("/internal/domain/CompanyReader/selectById1")
        CompanyRespDTO selectById1(@RequestBody SelectById1Request request);
    }

    @Bean
    @ConditionalOnExpression("'${tradepass.runtime.role:}' != 'identity'")
    CompanyReader remoteCompanyReader(Client client) {
        return new CompanyReader() {
            @Override public CompanyRespDTO selectById(Serializable id) { return client.selectById1(new SelectById1Request(id)); }
        };
    }

    @RestController
    @ConditionalOnProperty(name = "tradepass.runtime.role", havingValue = "identity")
    public static class Endpoint {
        private final CompanyReader operations;
        public Endpoint(CompanyReader operations) { this.operations = operations; }
        @PostMapping("/internal/domain/CompanyReader/selectById1")
        public CompanyRespDTO selectById1(@RequestBody SelectById1Request request) { return operations.selectById(request.id()); }
    }
}
