package com.tradepass.framework.rpc.core;

// Generated by scripts/generate-domain-rpc.py from tradepass-module-contract/tradepass-module-contract-api/src/main/java/com/tradepass/module/contract/api/directory/ContractDirectoryOperations.java.
import com.tradepass.module.contract.api.contract.dto.TradeContractRespDTO;
import java.util.List;
import com.tradepass.module.contract.api.directory.ContractDirectoryOperations;
import com.tradepass.module.contract.api.directory.ContractDirectoryOperations.*;
import com.tradepass.framework.rpc.config.DomainFeignConfiguration;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.context.annotation.*;
import org.springframework.boot.autoconfigure.condition.*;
import org.springframework.web.bind.annotation.*;

@Configuration(proxyBeanMethods = false)
@ConditionalOnProperty(name = "tradepass.services.split", havingValue = "true")
@Import(ContractDirectoryOperationsHttp.Endpoint.class)
public class ContractDirectoryOperationsHttp {
    public record ContractsByIds1Request(List<Long> ids) {}
    public record ActivePartyContracts1Request(long companyId) {}
    public record ActivePartyContractId2Request(long companyId, Long contractId) {}
    public record PartyContracts5Request(long companyId, String counterpartyName, String status, int limit, long offset) {}
    public record PartyContractCount3Request(long companyId, String counterpartyName, String status) {}

    @FeignClient(name = "${tradepass.services.contract-name:tradepass-contract}", contextId = "ContractDirectoryOperationsHttp",
            url = "${tradepass.services.contract-url:}", configuration = DomainFeignConfiguration.class)
    public interface Client {
        @PostMapping("/internal/domain/ContractDirectoryOperations/contractsByIds1")
        List<TradeContractRespDTO> contractsByIds1(@RequestBody ContractsByIds1Request request);
        @PostMapping("/internal/domain/ContractDirectoryOperations/activePartyContracts1")
        List<TradeContractRespDTO> activePartyContracts1(@RequestBody ActivePartyContracts1Request request);
        @PostMapping("/internal/domain/ContractDirectoryOperations/activePartyContractId2")
        Long activePartyContractId2(@RequestBody ActivePartyContractId2Request request);
        @PostMapping("/internal/domain/ContractDirectoryOperations/partyContracts5")
        List<TradeContractRespDTO> partyContracts5(@RequestBody PartyContracts5Request request);
        @PostMapping("/internal/domain/ContractDirectoryOperations/partyContractCount3")
        long partyContractCount3(@RequestBody PartyContractCount3Request request);
    }

    @Bean
    @ConditionalOnExpression("!T(com.tradepass.framework.common.core.HostedRoles).hosts('${tradepass.runtime.role:}', 'contract')")
    ContractDirectoryOperations remoteContractDirectoryOperations(Client client) {
        return new ContractDirectoryOperations() {
            @Override public List<TradeContractRespDTO> contractsByIds(List<Long> ids) { return client.contractsByIds1(new ContractsByIds1Request(ids)); }
            @Override public List<TradeContractRespDTO> activePartyContracts(long companyId) { return client.activePartyContracts1(new ActivePartyContracts1Request(companyId)); }
            @Override public Long activePartyContractId(long companyId, Long contractId) { return client.activePartyContractId2(new ActivePartyContractId2Request(companyId, contractId)); }
            @Override public List<TradeContractRespDTO> partyContracts(long companyId, String counterpartyName, String status, int limit, long offset) { return client.partyContracts5(new PartyContracts5Request(companyId, counterpartyName, status, limit, offset)); }
            @Override public long partyContractCount(long companyId, String counterpartyName, String status) { return client.partyContractCount3(new PartyContractCount3Request(companyId, counterpartyName, status)); }
        };
    }

    @RestController
    @ConditionalOnExpression("T(com.tradepass.framework.common.core.HostedRoles).hosts('${tradepass.runtime.role:}', 'contract')")
    public static class Endpoint {
        private final ContractDirectoryOperations operations;
        public Endpoint(ContractDirectoryOperations operations) { this.operations = operations; }
        @PostMapping("/internal/domain/ContractDirectoryOperations/contractsByIds1")
        public List<TradeContractRespDTO> contractsByIds1(@RequestBody ContractsByIds1Request request) { return operations.contractsByIds(request.ids()); }
        @PostMapping("/internal/domain/ContractDirectoryOperations/activePartyContracts1")
        public List<TradeContractRespDTO> activePartyContracts1(@RequestBody ActivePartyContracts1Request request) { return operations.activePartyContracts(request.companyId()); }
        @PostMapping("/internal/domain/ContractDirectoryOperations/activePartyContractId2")
        public Long activePartyContractId2(@RequestBody ActivePartyContractId2Request request) { return operations.activePartyContractId(request.companyId(), request.contractId()); }
        @PostMapping("/internal/domain/ContractDirectoryOperations/partyContracts5")
        public List<TradeContractRespDTO> partyContracts5(@RequestBody PartyContracts5Request request) { return operations.partyContracts(request.companyId(), request.counterpartyName(), request.status(), request.limit(), request.offset()); }
        @PostMapping("/internal/domain/ContractDirectoryOperations/partyContractCount3")
        public long partyContractCount3(@RequestBody PartyContractCount3Request request) { return operations.partyContractCount(request.companyId(), request.counterpartyName(), request.status()); }
    }
}
