package com.tradepass.framework.rpc.core;

// Generated by scripts/generate-domain-rpc.py from tradepass-module-contract/tradepass-module-contract-api/src/main/java/com/tradepass/module/contract/api/tenant/ContractTenantOperations.java.

import com.tradepass.module.contract.api.tenant.ContractTenantOperations;
import com.tradepass.module.contract.api.tenant.ContractTenantOperations.*;
import com.tradepass.framework.rpc.config.DomainFeignConfiguration;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.context.annotation.*;
import org.springframework.boot.autoconfigure.condition.*;
import org.springframework.web.bind.annotation.*;

@Configuration(proxyBeanMethods = false)
@ConditionalOnProperty(name = "tradepass.services.split", havingValue = "true")
@Import(ContractTenantOperationsHttp.Endpoint.class)
public class ContractTenantOperationsHttp {
    public record Initialize2Request(long companyId, long operatorUserId) {}

    @FeignClient(name = "${tradepass.services.contract-name:tradepass-contract}", contextId = "ContractTenantOperationsHttp",
            url = "${tradepass.services.contract-url:}", configuration = DomainFeignConfiguration.class)
    public interface Client {
        @PostMapping("/internal/domain/ContractTenantOperations/initialize2")
        void initialize2(@RequestBody Initialize2Request request);
    }

    @Bean
    @ConditionalOnExpression("!T(com.tradepass.framework.common.core.HostedRoles).hosts('${tradepass.runtime.role:}', 'contract')")
    ContractTenantOperations remoteContractTenantOperations(Client client) {
        return new ContractTenantOperations() {
            @Override public void initialize(long companyId, long operatorUserId) { client.initialize2(new Initialize2Request(companyId, operatorUserId)); }
        };
    }

    @RestController
    @ConditionalOnExpression("T(com.tradepass.framework.common.core.HostedRoles).hosts('${tradepass.runtime.role:}', 'contract')")
    public static class Endpoint {
        private final ContractTenantOperations operations;
        public Endpoint(ContractTenantOperations operations) { this.operations = operations; }
        @PostMapping("/internal/domain/ContractTenantOperations/initialize2")
        public void initialize2(@RequestBody Initialize2Request request) { operations.initialize(request.companyId(), request.operatorUserId()); }
    }
}
