package com.tradepass.framework.rpc.core;

// Generated by scripts/generate-domain-rpc.py from tradepass-module-contract/tradepass-module-contract-api/src/main/java/com/tradepass/module/contract/api/state/ContractStateOperations.java.

import com.tradepass.module.contract.api.state.ContractStateOperations;
import com.tradepass.module.contract.api.state.ContractStateOperations.*;
import com.tradepass.framework.rpc.config.DomainFeignConfiguration;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.context.annotation.*;
import org.springframework.boot.autoconfigure.condition.*;
import org.springframework.web.bind.annotation.*;

@Configuration(proxyBeanMethods = false)
@ConditionalOnProperty(name = "tradepass.services.split", havingValue = "true")
@Import(ContractStateOperationsHttp.Endpoint.class)
public class ContractStateOperationsHttp {
    public record ElectronicTaskCount1Request(Long contractId) {}
    public record ChangeActiveStatus2Request(Long contractId, String nextStatus) {}

    @FeignClient(name = "${tradepass.services.contract-name:tradepass-contract}", contextId = "ContractStateOperationsHttp",
            url = "${tradepass.services.contract-url:}", configuration = DomainFeignConfiguration.class)
    public interface Client {
        @PostMapping("/internal/domain/ContractStateOperations/electronicTaskCount1")
        long electronicTaskCount1(@RequestBody ElectronicTaskCount1Request request);
        @PostMapping("/internal/domain/ContractStateOperations/changeActiveStatus2")
        int changeActiveStatus2(@RequestBody ChangeActiveStatus2Request request);
    }

    @Bean
    @ConditionalOnExpression("!T(com.tradepass.framework.common.core.HostedRoles).hosts('${tradepass.runtime.role:}', 'contract')")
    ContractStateOperations remoteContractStateOperations(Client client) {
        return new ContractStateOperations() {
            @Override public long electronicTaskCount(Long contractId) { return client.electronicTaskCount1(new ElectronicTaskCount1Request(contractId)); }
            @Override public int changeActiveStatus(Long contractId, String nextStatus) { return client.changeActiveStatus2(new ChangeActiveStatus2Request(contractId, nextStatus)); }
        };
    }

    @RestController
    @ConditionalOnExpression("T(com.tradepass.framework.common.core.HostedRoles).hosts('${tradepass.runtime.role:}', 'contract')")
    public static class Endpoint {
        private final ContractStateOperations operations;
        public Endpoint(ContractStateOperations operations) { this.operations = operations; }
        @PostMapping("/internal/domain/ContractStateOperations/electronicTaskCount1")
        public long electronicTaskCount1(@RequestBody ElectronicTaskCount1Request request) { return operations.electronicTaskCount(request.contractId()); }
        @PostMapping("/internal/domain/ContractStateOperations/changeActiveStatus2")
        public int changeActiveStatus2(@RequestBody ChangeActiveStatus2Request request) { return operations.changeActiveStatus(request.contractId(), request.nextStatus()); }
    }
}
