package com.tradepass.framework.rpc.core;

// Generated by scripts/generate-domain-rpc.py from tradepass-module-contract/tradepass-module-contract-api/src/main/java/com/tradepass/module/contract/api/abolish/ContractAbolishRecoveryOperations.java.

import com.tradepass.module.contract.api.abolish.ContractAbolishRecoveryOperations;
import com.tradepass.module.contract.api.abolish.ContractAbolishRecoveryOperations.*;
import com.tradepass.framework.rpc.config.DomainFeignConfiguration;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.context.annotation.*;
import org.springframework.boot.autoconfigure.condition.*;
import org.springframework.web.bind.annotation.*;

@Configuration(proxyBeanMethods = false)
@ConditionalOnProperty(name = "tradepass.services.split", havingValue = "true")
@Import(ContractAbolishRecoveryOperationsHttp.Endpoint.class)
public class ContractAbolishRecoveryOperationsHttp {
    public record ResumeAfterBilateralApproval1Request(Long contractId) {}

    @FeignClient(name = "tradepass-contract", contextId = "ContractAbolishRecoveryOperationsHttp",
            url = "${tradepass.services.contract-url:}", configuration = DomainFeignConfiguration.class)
    public interface Client {
        @PostMapping("/internal/domain/ContractAbolishRecoveryOperations/resumeAfterBilateralApproval1")
        void resumeAfterBilateralApproval1(@RequestBody ResumeAfterBilateralApproval1Request request);
    }

    @Bean
    @ConditionalOnExpression("'${tradepass.runtime.role:}' != 'contract'")
    ContractAbolishRecoveryOperations remoteContractAbolishRecoveryOperations(Client client) {
        return new ContractAbolishRecoveryOperations() {
            @Override public void resumeAfterBilateralApproval(Long contractId) { client.resumeAfterBilateralApproval1(new ResumeAfterBilateralApproval1Request(contractId)); }
        };
    }

    @RestController
    @ConditionalOnProperty(name = "tradepass.runtime.role", havingValue = "contract")
    public static class Endpoint {
        private final ContractAbolishRecoveryOperations operations;
        public Endpoint(ContractAbolishRecoveryOperations operations) { this.operations = operations; }
        @PostMapping("/internal/domain/ContractAbolishRecoveryOperations/resumeAfterBilateralApproval1")
        public void resumeAfterBilateralApproval1(@RequestBody ResumeAfterBilateralApproval1Request request) { operations.resumeAfterBilateralApproval(request.contractId()); }
    }
}
