package com.tradepass.framework.rpc.core;

// Generated by scripts/generate-domain-rpc.py from tradepass-module-contract/tradepass-module-contract-api/src/main/java/com/tradepass/module/contract/api/contract/ContractReader.java.
import com.tradepass.module.contract.api.contract.dto.TradeContractRespDTO;
import java.io.Serializable;
import com.tradepass.module.contract.api.contract.ContractReader;
import com.tradepass.module.contract.api.contract.ContractReader.*;
import com.tradepass.framework.rpc.config.DomainFeignConfiguration;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.context.annotation.*;
import org.springframework.boot.autoconfigure.condition.*;
import org.springframework.web.bind.annotation.*;

@Configuration(proxyBeanMethods = false)
@ConditionalOnProperty(name = "tradepass.services.split", havingValue = "true")
@Import(ContractReaderHttp.Endpoint.class)
public class ContractReaderHttp {
    public record SelectById1Request(Serializable id) {}
    public record SelectByIdForUpdate1Request(Long id) {}
    public record CountContractsAwaitingSignature1Request(long companyId) {}

    @FeignClient(name = "tradepass-contract", contextId = "ContractReaderHttp",
            url = "${tradepass.services.contract-url:}", configuration = DomainFeignConfiguration.class)
    public interface Client {
        @PostMapping("/internal/domain/ContractReader/selectById1")
        TradeContractRespDTO selectById1(@RequestBody SelectById1Request request);
        @PostMapping("/internal/domain/ContractReader/selectByIdForUpdate1")
        TradeContractRespDTO selectByIdForUpdate1(@RequestBody SelectByIdForUpdate1Request request);
        @PostMapping("/internal/domain/ContractReader/countContractsAwaitingSignature1")
        long countContractsAwaitingSignature1(@RequestBody CountContractsAwaitingSignature1Request request);
    }

    @Bean
    @ConditionalOnExpression("'${tradepass.runtime.role:}' != 'contract'")
    ContractReader remoteContractReader(Client client) {
        return new ContractReader() {
            @Override public TradeContractRespDTO selectById(Serializable id) { return client.selectById1(new SelectById1Request(id)); }
            @Override public TradeContractRespDTO selectByIdForUpdate(Long id) { return client.selectByIdForUpdate1(new SelectByIdForUpdate1Request(id)); }
            @Override public long countContractsAwaitingSignature(long companyId) { return client.countContractsAwaitingSignature1(new CountContractsAwaitingSignature1Request(companyId)); }
        };
    }

    @RestController
    @ConditionalOnProperty(name = "tradepass.runtime.role", havingValue = "contract")
    public static class Endpoint {
        private final ContractReader operations;
        public Endpoint(ContractReader operations) { this.operations = operations; }
        @PostMapping("/internal/domain/ContractReader/selectById1")
        public TradeContractRespDTO selectById1(@RequestBody SelectById1Request request) { return operations.selectById(request.id()); }
        @PostMapping("/internal/domain/ContractReader/selectByIdForUpdate1")
        public TradeContractRespDTO selectByIdForUpdate1(@RequestBody SelectByIdForUpdate1Request request) { return operations.selectByIdForUpdate(request.id()); }
        @PostMapping("/internal/domain/ContractReader/countContractsAwaitingSignature1")
        public long countContractsAwaitingSignature1(@RequestBody CountContractsAwaitingSignature1Request request) { return operations.countContractsAwaitingSignature(request.companyId()); }
    }
}
