package com.tradepass.framework.rpc.core;

// Generated by scripts/generate-domain-rpc.py from tradepass-module-settlement/tradepass-module-settlement-api/src/main/java/com/tradepass/module/settlement/api/attachment/ContractAttachmentOperations.java.
import com.tradepass.framework.common.util.FileTypeInspector;
import com.tradepass.module.settlement.enums.AttachmentCategoryEnum;
import java.util.List;
import java.util.Map;
import com.tradepass.module.settlement.api.attachment.ContractAttachmentOperations;
import com.tradepass.module.settlement.api.attachment.ContractAttachmentOperations.*;
import com.tradepass.framework.rpc.config.DomainFeignConfiguration;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.context.annotation.*;
import org.springframework.boot.autoconfigure.condition.*;
import org.springframework.web.bind.annotation.*;

@Configuration(proxyBeanMethods = false)
@ConditionalOnProperty(name = "tradepass.services.split", havingValue = "true")
@Import(ContractAttachmentOperationsHttp.Endpoint.class)
public class ContractAttachmentOperationsHttp {
    public record List2Request(Long contractId, String category) {}
    public record Upload6Request(Long contractId, String category, String originalName, byte[] data, String voucherDate, String voucherAmount) {}
    public record Upload9Request(Long contractId, String category, String originalName, byte[] data, String voucherDate, String voucherAmount, String invoiceNo, String invoiceDate, String invoiceAmount) {}
    public record Decide3Request(Long id, String decision, String reason) {}
    public record Decide5Request(Long id, String decision, String reason, String signatureName, byte[] signatureData) {}
    public record Withdraw1Request(Long id) {}
    public record Delete1Request(Long id) {}
    public record GetFile1Request(Long id) {}

    @FeignClient(name = "${tradepass.services.settlement-name:tradepass-settlement}", contextId = "ContractAttachmentOperationsHttp",
            url = "${tradepass.services.settlement-url:}", configuration = DomainFeignConfiguration.class)
    public interface Client {
        @PostMapping("/internal/domain/ContractAttachmentOperations/list2")
        List<Map<String, Object>> list2(@RequestBody List2Request request);
        @PostMapping("/internal/domain/ContractAttachmentOperations/upload6")
        Map<String, Object> upload6(@RequestBody Upload6Request request);
        @PostMapping("/internal/domain/ContractAttachmentOperations/upload9")
        Map<String, Object> upload9(@RequestBody Upload9Request request);
        @PostMapping("/internal/domain/ContractAttachmentOperations/decide3")
        Map<String, Object> decide3(@RequestBody Decide3Request request);
        @PostMapping("/internal/domain/ContractAttachmentOperations/decide5")
        Map<String, Object> decide5(@RequestBody Decide5Request request);
        @PostMapping("/internal/domain/ContractAttachmentOperations/withdraw1")
        String withdraw1(@RequestBody Withdraw1Request request);
        @PostMapping("/internal/domain/ContractAttachmentOperations/delete1")
        String delete1(@RequestBody Delete1Request request);
        @PostMapping("/internal/domain/ContractAttachmentOperations/getFile1")
        FileRespDTO getFile1(@RequestBody GetFile1Request request);
    }

    @Bean
    @ConditionalOnExpression("!T(com.tradepass.framework.common.core.HostedRoles).hosts('${tradepass.runtime.role:}', 'settlement')")
    ContractAttachmentOperations remoteContractAttachmentOperations(Client client) {
        return new ContractAttachmentOperations() {
            @Override public List<Map<String, Object>> list(Long contractId, String category) { return client.list2(new List2Request(contractId, category)); }
            @Override public Map<String, Object> upload(Long contractId, String category, String originalName, byte[] data, String voucherDate, String voucherAmount) { return client.upload6(new Upload6Request(contractId, category, originalName, data, voucherDate, voucherAmount)); }
            @Override public Map<String, Object> upload(Long contractId, String category, String originalName, byte[] data, String voucherDate, String voucherAmount, String invoiceNo, String invoiceDate, String invoiceAmount) { return client.upload9(new Upload9Request(contractId, category, originalName, data, voucherDate, voucherAmount, invoiceNo, invoiceDate, invoiceAmount)); }
            @Override public Map<String, Object> decide(Long id, String decision, String reason) { return client.decide3(new Decide3Request(id, decision, reason)); }
            @Override public Map<String, Object> decide(Long id, String decision, String reason, String signatureName, byte[] signatureData) { return client.decide5(new Decide5Request(id, decision, reason, signatureName, signatureData)); }
            @Override public String withdraw(Long id) { return client.withdraw1(new Withdraw1Request(id)); }
            @Override public String delete(Long id) { return client.delete1(new Delete1Request(id)); }
            @Override public FileRespDTO getFile(Long id) { return client.getFile1(new GetFile1Request(id)); }
        };
    }

    @RestController
    @ConditionalOnExpression("T(com.tradepass.framework.common.core.HostedRoles).hosts('${tradepass.runtime.role:}', 'settlement')")
    public static class Endpoint {
        private final ContractAttachmentOperations operations;
        public Endpoint(ContractAttachmentOperations operations) { this.operations = operations; }
        @PostMapping("/internal/domain/ContractAttachmentOperations/list2")
        public List<Map<String, Object>> list2(@RequestBody List2Request request) { return operations.list(request.contractId(), request.category()); }
        @PostMapping("/internal/domain/ContractAttachmentOperations/upload6")
        public Map<String, Object> upload6(@RequestBody Upload6Request request) { return operations.upload(request.contractId(), request.category(), request.originalName(), request.data(), request.voucherDate(), request.voucherAmount()); }
        @PostMapping("/internal/domain/ContractAttachmentOperations/upload9")
        public Map<String, Object> upload9(@RequestBody Upload9Request request) { return operations.upload(request.contractId(), request.category(), request.originalName(), request.data(), request.voucherDate(), request.voucherAmount(), request.invoiceNo(), request.invoiceDate(), request.invoiceAmount()); }
        @PostMapping("/internal/domain/ContractAttachmentOperations/decide3")
        public Map<String, Object> decide3(@RequestBody Decide3Request request) { return operations.decide(request.id(), request.decision(), request.reason()); }
        @PostMapping("/internal/domain/ContractAttachmentOperations/decide5")
        public Map<String, Object> decide5(@RequestBody Decide5Request request) { return operations.decide(request.id(), request.decision(), request.reason(), request.signatureName(), request.signatureData()); }
        @PostMapping("/internal/domain/ContractAttachmentOperations/withdraw1")
        public String withdraw1(@RequestBody Withdraw1Request request) { return operations.withdraw(request.id()); }
        @PostMapping("/internal/domain/ContractAttachmentOperations/delete1")
        public String delete1(@RequestBody Delete1Request request) { return operations.delete(request.id()); }
        @PostMapping("/internal/domain/ContractAttachmentOperations/getFile1")
        public FileRespDTO getFile1(@RequestBody GetFile1Request request) { return operations.getFile(request.id()); }
    }
}
