package com.tradepass.framework.rpc.core;

// Generated by scripts/generate-domain-rpc.py from tradepass-module-identity/tradepass-module-identity-api/src/main/java/com/tradepass/module/identity/api/counterparty/CounterpartyReader.java.

import com.tradepass.module.identity.api.counterparty.CounterpartyReader;
import com.tradepass.module.identity.api.counterparty.CounterpartyReader.*;
import com.tradepass.framework.rpc.config.DomainFeignConfiguration;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.context.annotation.*;
import org.springframework.boot.autoconfigure.condition.*;
import org.springframework.web.bind.annotation.*;

@Configuration(proxyBeanMethods = false)
@ConditionalOnProperty(name = "tradepass.services.split", havingValue = "true")
@Import(CounterpartyReaderHttp.Endpoint.class)
public class CounterpartyReaderHttp {
    public record CountActiveBetween2Request(Long leftCompanyId, Long rightCompanyId) {}

    @FeignClient(name = "tradepass-identity", contextId = "CounterpartyReaderHttp",
            url = "${tradepass.services.identity-url:}", configuration = DomainFeignConfiguration.class)
    public interface Client {
        @PostMapping("/internal/domain/CounterpartyReader/countActiveBetween2")
        long countActiveBetween2(@RequestBody CountActiveBetween2Request request);
    }

    @Bean
    @ConditionalOnExpression("'${tradepass.runtime.role:}' != 'identity'")
    CounterpartyReader remoteCounterpartyReader(Client client) {
        return new CounterpartyReader() {
            @Override public long countActiveBetween(Long leftCompanyId, Long rightCompanyId) { return client.countActiveBetween2(new CountActiveBetween2Request(leftCompanyId, rightCompanyId)); }
        };
    }

    @RestController
    @ConditionalOnProperty(name = "tradepass.runtime.role", havingValue = "identity")
    public static class Endpoint {
        private final CounterpartyReader operations;
        public Endpoint(CounterpartyReader operations) { this.operations = operations; }
        @PostMapping("/internal/domain/CounterpartyReader/countActiveBetween2")
        public long countActiveBetween2(@RequestBody CountActiveBetween2Request request) { return operations.countActiveBetween(request.leftCompanyId(), request.rightCompanyId()); }
    }
}
