package com.tradepass.framework.rpc.core;

// Generated by scripts/generate-domain-rpc.py from tradepass-module-trade/tradepass-module-trade-api/src/main/java/com/tradepass/module/trade/api/document/DocumentTodoReader.java.
import com.tradepass.module.trade.api.document.dto.BusinessDocumentRespDTO;
import com.tradepass.module.trade.api.document.DocumentTodoReader;
import com.tradepass.module.trade.api.document.DocumentTodoReader.*;
import com.tradepass.framework.rpc.config.DomainFeignConfiguration;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.context.annotation.*;
import org.springframework.boot.autoconfigure.condition.*;
import org.springframework.web.bind.annotation.*;

@Configuration(proxyBeanMethods = false)
@ConditionalOnProperty(name = "tradepass.services.split", havingValue = "true")
@Import(DocumentTodoReaderHttp.Endpoint.class)
public class DocumentTodoReaderHttp {
    public record PendingDocumentCount1Request(long companyId) {}
    public record LatestPendingDocument1Request(long companyId) {}

    @FeignClient(name = "tradepass-trade", contextId = "DocumentTodoReaderHttp",
            url = "${tradepass.services.trade-url:}", configuration = DomainFeignConfiguration.class)
    public interface Client {
        @PostMapping("/internal/domain/DocumentTodoReader/pendingDocumentCount1")
        long pendingDocumentCount1(@RequestBody PendingDocumentCount1Request request);
        @PostMapping("/internal/domain/DocumentTodoReader/latestPendingDocument1")
        BusinessDocumentRespDTO latestPendingDocument1(@RequestBody LatestPendingDocument1Request request);
    }

    @Bean
    @ConditionalOnExpression("'${tradepass.runtime.role:}' != 'trade'")
    DocumentTodoReader remoteDocumentTodoReader(Client client) {
        return new DocumentTodoReader() {
            @Override public long pendingDocumentCount(long companyId) { return client.pendingDocumentCount1(new PendingDocumentCount1Request(companyId)); }
            @Override public BusinessDocumentRespDTO latestPendingDocument(long companyId) { return client.latestPendingDocument1(new LatestPendingDocument1Request(companyId)); }
        };
    }

    @RestController
    @ConditionalOnProperty(name = "tradepass.runtime.role", havingValue = "trade")
    public static class Endpoint {
        private final DocumentTodoReader operations;
        public Endpoint(DocumentTodoReader operations) { this.operations = operations; }
        @PostMapping("/internal/domain/DocumentTodoReader/pendingDocumentCount1")
        public long pendingDocumentCount1(@RequestBody PendingDocumentCount1Request request) { return operations.pendingDocumentCount(request.companyId()); }
        @PostMapping("/internal/domain/DocumentTodoReader/latestPendingDocument1")
        public BusinessDocumentRespDTO latestPendingDocument1(@RequestBody LatestPendingDocument1Request request) { return operations.latestPendingDocument(request.companyId()); }
    }
}
