package com.tradepass.framework.rpc.core;

// Generated by scripts/generate-domain-rpc.py from tradepass-module-trade/tradepass-module-trade-api/src/main/java/com/tradepass/module/trade/api/document/DocumentTenantOperations.java.

import com.tradepass.module.trade.api.document.DocumentTenantOperations;
import com.tradepass.module.trade.api.document.DocumentTenantOperations.*;
import com.tradepass.framework.rpc.config.DomainFeignConfiguration;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.context.annotation.*;
import org.springframework.boot.autoconfigure.condition.*;
import org.springframework.web.bind.annotation.*;

@Configuration(proxyBeanMethods = false)
@ConditionalOnProperty(name = "tradepass.services.split", havingValue = "true")
@Import(DocumentTenantOperationsHttp.Endpoint.class)
public class DocumentTenantOperationsHttp {
    public record Initialize2Request(long companyId, long operatorUserId) {}

    @FeignClient(name = "tradepass-trade", contextId = "DocumentTenantOperationsHttp",
            url = "${tradepass.services.trade-url:}", configuration = DomainFeignConfiguration.class)
    public interface Client {
        @PostMapping("/internal/domain/DocumentTenantOperations/initialize2")
        void initialize2(@RequestBody Initialize2Request request);
    }

    @Bean
    @ConditionalOnExpression("'${tradepass.runtime.role:}' != 'trade'")
    DocumentTenantOperations remoteDocumentTenantOperations(Client client) {
        return new DocumentTenantOperations() {
            @Override public void initialize(long companyId, long operatorUserId) { client.initialize2(new Initialize2Request(companyId, operatorUserId)); }
        };
    }

    @RestController
    @ConditionalOnProperty(name = "tradepass.runtime.role", havingValue = "trade")
    public static class Endpoint {
        private final DocumentTenantOperations operations;
        public Endpoint(DocumentTenantOperations operations) { this.operations = operations; }
        @PostMapping("/internal/domain/DocumentTenantOperations/initialize2")
        public void initialize2(@RequestBody Initialize2Request request) { operations.initialize(request.companyId(), request.operatorUserId()); }
    }
}
