package com.tradepass.framework.rpc.core;

// Generated by scripts/generate-domain-rpc.py from tradepass-module-identity/tradepass-module-identity-api/src/main/java/com/tradepass/module/identity/api/fadada/FadadaPersonalIdentityOperations.java.
import com.fasterxml.jackson.databind.JsonNode;
import com.tradepass.module.identity.api.fadada.dto.FadadaAuthUrlRespDTO;
import com.tradepass.module.identity.api.fadada.dto.PersonalIdentityRespDTO;
import com.tradepass.module.identity.api.fadada.FadadaPersonalIdentityOperations;
import com.tradepass.module.identity.api.fadada.FadadaPersonalIdentityOperations.*;
import com.tradepass.framework.rpc.config.DomainFeignConfiguration;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.context.annotation.*;
import org.springframework.boot.autoconfigure.condition.*;
import org.springframework.web.bind.annotation.*;

@Configuration(proxyBeanMethods = false)
@ConditionalOnProperty(name = "tradepass.services.split", havingValue = "true")
@Import(FadadaPersonalIdentityOperationsHttp.Endpoint.class)
public class FadadaPersonalIdentityOperationsHttp {
    public record Current0Request() {}
    public record SyncCurrent0Request() {}
    public record RequireCurrentVerified0Request() {}
    public record VerifiedOpenUserId1Request(long userId) {}
    public record CreateAuthUrl0Request() {}
    public record SyncByClientUserId1Request(String clientUserId) {}
    public record SyncCallback2Request(String clientUserId, JsonNode data) {}

    @FeignClient(name = "${tradepass.services.identity-name:tradepass-identity}", contextId = "FadadaPersonalIdentityOperationsHttp",
            url = "${tradepass.services.identity-url:}", configuration = DomainFeignConfiguration.class)
    public interface Client {
        @PostMapping("/internal/domain/FadadaPersonalIdentityOperations/current0")
        PersonalIdentityRespDTO current0(@RequestBody Current0Request request);
        @PostMapping("/internal/domain/FadadaPersonalIdentityOperations/syncCurrent0")
        PersonalIdentityRespDTO syncCurrent0(@RequestBody SyncCurrent0Request request);
        @PostMapping("/internal/domain/FadadaPersonalIdentityOperations/requireCurrentVerified0")
        PersonalIdentityRespDTO requireCurrentVerified0(@RequestBody RequireCurrentVerified0Request request);
        @PostMapping("/internal/domain/FadadaPersonalIdentityOperations/verifiedOpenUserId1")
        String verifiedOpenUserId1(@RequestBody VerifiedOpenUserId1Request request);
        @PostMapping("/internal/domain/FadadaPersonalIdentityOperations/createAuthUrl0")
        FadadaAuthUrlRespDTO createAuthUrl0(@RequestBody CreateAuthUrl0Request request);
        @PostMapping("/internal/domain/FadadaPersonalIdentityOperations/syncByClientUserId1")
        PersonalIdentityRespDTO syncByClientUserId1(@RequestBody SyncByClientUserId1Request request);
        @PostMapping("/internal/domain/FadadaPersonalIdentityOperations/syncCallback2")
        PersonalIdentityRespDTO syncCallback2(@RequestBody SyncCallback2Request request);
    }

    @Bean
    @ConditionalOnExpression("!T(com.tradepass.framework.common.core.HostedRoles).hosts('${tradepass.runtime.role:}', 'identity')")
    FadadaPersonalIdentityOperations remoteFadadaPersonalIdentityOperations(Client client) {
        return new FadadaPersonalIdentityOperations() {
            @Override public PersonalIdentityRespDTO current() { return client.current0(new Current0Request()); }
            @Override public PersonalIdentityRespDTO syncCurrent() { return client.syncCurrent0(new SyncCurrent0Request()); }
            @Override public PersonalIdentityRespDTO requireCurrentVerified() { return client.requireCurrentVerified0(new RequireCurrentVerified0Request()); }
            @Override public String verifiedOpenUserId(long userId) { return client.verifiedOpenUserId1(new VerifiedOpenUserId1Request(userId)); }
            @Override public FadadaAuthUrlRespDTO createAuthUrl() { return client.createAuthUrl0(new CreateAuthUrl0Request()); }
            @Override public PersonalIdentityRespDTO syncByClientUserId(String clientUserId) { return client.syncByClientUserId1(new SyncByClientUserId1Request(clientUserId)); }
            @Override public PersonalIdentityRespDTO syncCallback(String clientUserId, JsonNode data) { return client.syncCallback2(new SyncCallback2Request(clientUserId, data)); }
        };
    }

    @RestController
    @ConditionalOnExpression("T(com.tradepass.framework.common.core.HostedRoles).hosts('${tradepass.runtime.role:}', 'identity')")
    public static class Endpoint {
        private final FadadaPersonalIdentityOperations operations;
        public Endpoint(FadadaPersonalIdentityOperations operations) { this.operations = operations; }
        @PostMapping("/internal/domain/FadadaPersonalIdentityOperations/current0")
        public PersonalIdentityRespDTO current0(@RequestBody Current0Request request) { return operations.current(); }
        @PostMapping("/internal/domain/FadadaPersonalIdentityOperations/syncCurrent0")
        public PersonalIdentityRespDTO syncCurrent0(@RequestBody SyncCurrent0Request request) { return operations.syncCurrent(); }
        @PostMapping("/internal/domain/FadadaPersonalIdentityOperations/requireCurrentVerified0")
        public PersonalIdentityRespDTO requireCurrentVerified0(@RequestBody RequireCurrentVerified0Request request) { return operations.requireCurrentVerified(); }
        @PostMapping("/internal/domain/FadadaPersonalIdentityOperations/verifiedOpenUserId1")
        public String verifiedOpenUserId1(@RequestBody VerifiedOpenUserId1Request request) { return operations.verifiedOpenUserId(request.userId()); }
        @PostMapping("/internal/domain/FadadaPersonalIdentityOperations/createAuthUrl0")
        public FadadaAuthUrlRespDTO createAuthUrl0(@RequestBody CreateAuthUrl0Request request) { return operations.createAuthUrl(); }
        @PostMapping("/internal/domain/FadadaPersonalIdentityOperations/syncByClientUserId1")
        public PersonalIdentityRespDTO syncByClientUserId1(@RequestBody SyncByClientUserId1Request request) { return operations.syncByClientUserId(request.clientUserId()); }
        @PostMapping("/internal/domain/FadadaPersonalIdentityOperations/syncCallback2")
        public PersonalIdentityRespDTO syncCallback2(@RequestBody SyncCallback2Request request) { return operations.syncCallback(request.clientUserId(), request.data()); }
    }
}
