package com.tradepass.framework.rpc.core;

// Generated by scripts/generate-domain-rpc.py from tradepass-module-contract/tradepass-module-contract-api/src/main/java/com/tradepass/module/contract/api/signing/FadadaContractSigningOperations.java.
import com.tradepass.module.contract.api.signing.dto.ContractSigningRespDTO;
import com.tradepass.framework.common.pojo.ServiceUrlPayload;
import com.tradepass.module.contract.api.signing.FadadaContractSigningOperations;
import com.tradepass.module.contract.api.signing.FadadaContractSigningOperations.*;
import com.tradepass.framework.rpc.config.DomainFeignConfiguration;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.context.annotation.*;
import org.springframework.boot.autoconfigure.condition.*;
import org.springframework.web.bind.annotation.*;

@Configuration(proxyBeanMethods = false)
@ConditionalOnProperty(name = "tradepass.services.split", havingValue = "true")
@Import(FadadaContractSigningOperationsHttp.Endpoint.class)
public class FadadaContractSigningOperationsHttp {
    public record Current1Request(Long contractId) {}
    public record SignUrl1Request(Long contractId) {}
    public record SyncCurrent1Request(Long contractId) {}
    public record SignedPreview1Request(Long contractId) {}
    public record SyncBySignTaskId1Request(String signTaskId) {}
    public record AbolishUrl2Request(Long contractId, String reason) {}

    @FeignClient(name = "tradepass-contract", contextId = "FadadaContractSigningOperationsHttp",
            url = "${tradepass.services.contract-url:}", configuration = DomainFeignConfiguration.class)
    public interface Client {
        @PostMapping("/internal/domain/FadadaContractSigningOperations/current1")
        ContractSigningRespDTO current1(@RequestBody Current1Request request);
        @PostMapping("/internal/domain/FadadaContractSigningOperations/signUrl1")
        ServiceUrlPayload signUrl1(@RequestBody SignUrl1Request request);
        @PostMapping("/internal/domain/FadadaContractSigningOperations/syncCurrent1")
        ContractSigningRespDTO syncCurrent1(@RequestBody SyncCurrent1Request request);
        @PostMapping("/internal/domain/FadadaContractSigningOperations/signedPreview1")
        SignedPreview signedPreview1(@RequestBody SignedPreview1Request request);
        @PostMapping("/internal/domain/FadadaContractSigningOperations/syncBySignTaskId1")
        void syncBySignTaskId1(@RequestBody SyncBySignTaskId1Request request);
        @PostMapping("/internal/domain/FadadaContractSigningOperations/abolishUrl2")
        ServiceUrlPayload abolishUrl2(@RequestBody AbolishUrl2Request request);
    }

    @Bean
    @ConditionalOnExpression("'${tradepass.runtime.role:}' != 'contract'")
    FadadaContractSigningOperations remoteFadadaContractSigningOperations(Client client) {
        return new FadadaContractSigningOperations() {
            @Override public ContractSigningRespDTO current(Long contractId) { return client.current1(new Current1Request(contractId)); }
            @Override public ServiceUrlPayload signUrl(Long contractId) { return client.signUrl1(new SignUrl1Request(contractId)); }
            @Override public ContractSigningRespDTO syncCurrent(Long contractId) { return client.syncCurrent1(new SyncCurrent1Request(contractId)); }
            @Override public SignedPreview signedPreview(Long contractId) { return client.signedPreview1(new SignedPreview1Request(contractId)); }
            @Override public void syncBySignTaskId(String signTaskId) { client.syncBySignTaskId1(new SyncBySignTaskId1Request(signTaskId)); }
            @Override public ServiceUrlPayload abolishUrl(Long contractId, String reason) { return client.abolishUrl2(new AbolishUrl2Request(contractId, reason)); }
        };
    }

    @RestController
    @ConditionalOnProperty(name = "tradepass.runtime.role", havingValue = "contract")
    public static class Endpoint {
        private final FadadaContractSigningOperations operations;
        public Endpoint(FadadaContractSigningOperations operations) { this.operations = operations; }
        @PostMapping("/internal/domain/FadadaContractSigningOperations/current1")
        public ContractSigningRespDTO current1(@RequestBody Current1Request request) { return operations.current(request.contractId()); }
        @PostMapping("/internal/domain/FadadaContractSigningOperations/signUrl1")
        public ServiceUrlPayload signUrl1(@RequestBody SignUrl1Request request) { return operations.signUrl(request.contractId()); }
        @PostMapping("/internal/domain/FadadaContractSigningOperations/syncCurrent1")
        public ContractSigningRespDTO syncCurrent1(@RequestBody SyncCurrent1Request request) { return operations.syncCurrent(request.contractId()); }
        @PostMapping("/internal/domain/FadadaContractSigningOperations/signedPreview1")
        public SignedPreview signedPreview1(@RequestBody SignedPreview1Request request) { return operations.signedPreview(request.contractId()); }
        @PostMapping("/internal/domain/FadadaContractSigningOperations/syncBySignTaskId1")
        public void syncBySignTaskId1(@RequestBody SyncBySignTaskId1Request request) { operations.syncBySignTaskId(request.signTaskId()); }
        @PostMapping("/internal/domain/FadadaContractSigningOperations/abolishUrl2")
        public ServiceUrlPayload abolishUrl2(@RequestBody AbolishUrl2Request request) { return operations.abolishUrl(request.contractId(), request.reason()); }
    }
}
