package com.tradepass.framework.rpc.core;

// Generated by scripts/generate-domain-rpc.py from tradepass-module-identity/tradepass-module-identity-api/src/main/java/com/tradepass/module/identity/api/fadada/FadadaCompanyOperations.java.
import com.fasterxml.jackson.databind.JsonNode;
import com.tradepass.module.identity.api.fadada.dto.FadadaCompanyIdentityRespDTO;
import com.tradepass.module.identity.api.fadada.dto.LegalRepresentativeRespDTO;
import com.tradepass.framework.common.pojo.ServiceUrlPayload;
import com.tradepass.module.identity.api.fadada.dto.FadadaCorpIdentityRespDTO;
import com.tradepass.module.identity.api.fadada.FadadaCompanyOperations;
import com.tradepass.module.identity.api.fadada.FadadaCompanyOperations.*;
import com.tradepass.framework.rpc.config.DomainFeignConfiguration;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.context.annotation.*;
import org.springframework.boot.autoconfigure.condition.*;
import org.springframework.web.bind.annotation.*;

@Configuration(proxyBeanMethods = false)
@ConditionalOnProperty(name = "tradepass.services.split", havingValue = "true")
@Import(FadadaCompanyOperationsHttp.Endpoint.class)
public class FadadaCompanyOperationsHttp {
    public record Current1Request(long companyId) {}
    public record CreateAuthUrl1Request(long companyId) {}
    public record SyncCurrent1Request(long companyId) {}
    public record CreateLegalRepresentativeUrl1Request(long companyId) {}
    public record SyncLegalRepresentative1Request(long companyId) {}
    public record Sync1Request(long companyId) {}
    public record SyncByClientCorpId1Request(String clientCorpId) {}
    public record SyncByOpenCorpId1Request(String openCorpId) {}
    public record SyncCallback3Request(String clientCorpId, String openCorpId, JsonNode data) {}
    public record CreateSealManageUrl1Request(long companyId) {}
    public record RequireVerified1Request(long companyId) {}
    public record EnabledSealId1Request(long companyId) {}

    @FeignClient(name = "${tradepass.services.identity-name:tradepass-identity}", contextId = "FadadaCompanyOperationsHttp",
            url = "${tradepass.services.identity-url:}", configuration = DomainFeignConfiguration.class)
    public interface Client {
        @PostMapping("/internal/domain/FadadaCompanyOperations/current1")
        FadadaCompanyIdentityRespDTO current1(@RequestBody Current1Request request);
        @PostMapping("/internal/domain/FadadaCompanyOperations/createAuthUrl1")
        ServiceUrlPayload createAuthUrl1(@RequestBody CreateAuthUrl1Request request);
        @PostMapping("/internal/domain/FadadaCompanyOperations/syncCurrent1")
        FadadaCompanyIdentityRespDTO syncCurrent1(@RequestBody SyncCurrent1Request request);
        @PostMapping("/internal/domain/FadadaCompanyOperations/createLegalRepresentativeUrl1")
        ServiceUrlPayload createLegalRepresentativeUrl1(@RequestBody CreateLegalRepresentativeUrl1Request request);
        @PostMapping("/internal/domain/FadadaCompanyOperations/syncLegalRepresentative1")
        LegalRepresentativeRespDTO syncLegalRepresentative1(@RequestBody SyncLegalRepresentative1Request request);
        @PostMapping("/internal/domain/FadadaCompanyOperations/sync1")
        FadadaCompanyIdentityRespDTO sync1(@RequestBody Sync1Request request);
        @PostMapping("/internal/domain/FadadaCompanyOperations/syncByClientCorpId1")
        FadadaCompanyIdentityRespDTO syncByClientCorpId1(@RequestBody SyncByClientCorpId1Request request);
        @PostMapping("/internal/domain/FadadaCompanyOperations/syncByOpenCorpId1")
        FadadaCompanyIdentityRespDTO syncByOpenCorpId1(@RequestBody SyncByOpenCorpId1Request request);
        @PostMapping("/internal/domain/FadadaCompanyOperations/syncCallback3")
        FadadaCompanyIdentityRespDTO syncCallback3(@RequestBody SyncCallback3Request request);
        @PostMapping("/internal/domain/FadadaCompanyOperations/createSealManageUrl1")
        ServiceUrlPayload createSealManageUrl1(@RequestBody CreateSealManageUrl1Request request);
        @PostMapping("/internal/domain/FadadaCompanyOperations/requireVerified1")
        FadadaCorpIdentityRespDTO requireVerified1(@RequestBody RequireVerified1Request request);
        @PostMapping("/internal/domain/FadadaCompanyOperations/enabledSealId1")
        String enabledSealId1(@RequestBody EnabledSealId1Request request);
    }

    @Bean
    @ConditionalOnExpression("!T(com.tradepass.framework.common.core.HostedRoles).hosts('${tradepass.runtime.role:}', 'identity')")
    FadadaCompanyOperations remoteFadadaCompanyOperations(Client client) {
        return new FadadaCompanyOperations() {
            @Override public FadadaCompanyIdentityRespDTO current(long companyId) { return client.current1(new Current1Request(companyId)); }
            @Override public ServiceUrlPayload createAuthUrl(long companyId) { return client.createAuthUrl1(new CreateAuthUrl1Request(companyId)); }
            @Override public FadadaCompanyIdentityRespDTO syncCurrent(long companyId) { return client.syncCurrent1(new SyncCurrent1Request(companyId)); }
            @Override public ServiceUrlPayload createLegalRepresentativeUrl(long companyId) { return client.createLegalRepresentativeUrl1(new CreateLegalRepresentativeUrl1Request(companyId)); }
            @Override public LegalRepresentativeRespDTO syncLegalRepresentative(long companyId) { return client.syncLegalRepresentative1(new SyncLegalRepresentative1Request(companyId)); }
            @Override public FadadaCompanyIdentityRespDTO sync(long companyId) { return client.sync1(new Sync1Request(companyId)); }
            @Override public FadadaCompanyIdentityRespDTO syncByClientCorpId(String clientCorpId) { return client.syncByClientCorpId1(new SyncByClientCorpId1Request(clientCorpId)); }
            @Override public FadadaCompanyIdentityRespDTO syncByOpenCorpId(String openCorpId) { return client.syncByOpenCorpId1(new SyncByOpenCorpId1Request(openCorpId)); }
            @Override public FadadaCompanyIdentityRespDTO syncCallback(String clientCorpId, String openCorpId, JsonNode data) { return client.syncCallback3(new SyncCallback3Request(clientCorpId, openCorpId, data)); }
            @Override public ServiceUrlPayload createSealManageUrl(long companyId) { return client.createSealManageUrl1(new CreateSealManageUrl1Request(companyId)); }
            @Override public FadadaCorpIdentityRespDTO requireVerified(long companyId) { return client.requireVerified1(new RequireVerified1Request(companyId)); }
            @Override public String enabledSealId(long companyId) { return client.enabledSealId1(new EnabledSealId1Request(companyId)); }
        };
    }

    @RestController
    @ConditionalOnExpression("T(com.tradepass.framework.common.core.HostedRoles).hosts('${tradepass.runtime.role:}', 'identity')")
    public static class Endpoint {
        private final FadadaCompanyOperations operations;
        public Endpoint(FadadaCompanyOperations operations) { this.operations = operations; }
        @PostMapping("/internal/domain/FadadaCompanyOperations/current1")
        public FadadaCompanyIdentityRespDTO current1(@RequestBody Current1Request request) { return operations.current(request.companyId()); }
        @PostMapping("/internal/domain/FadadaCompanyOperations/createAuthUrl1")
        public ServiceUrlPayload createAuthUrl1(@RequestBody CreateAuthUrl1Request request) { return operations.createAuthUrl(request.companyId()); }
        @PostMapping("/internal/domain/FadadaCompanyOperations/syncCurrent1")
        public FadadaCompanyIdentityRespDTO syncCurrent1(@RequestBody SyncCurrent1Request request) { return operations.syncCurrent(request.companyId()); }
        @PostMapping("/internal/domain/FadadaCompanyOperations/createLegalRepresentativeUrl1")
        public ServiceUrlPayload createLegalRepresentativeUrl1(@RequestBody CreateLegalRepresentativeUrl1Request request) { return operations.createLegalRepresentativeUrl(request.companyId()); }
        @PostMapping("/internal/domain/FadadaCompanyOperations/syncLegalRepresentative1")
        public LegalRepresentativeRespDTO syncLegalRepresentative1(@RequestBody SyncLegalRepresentative1Request request) { return operations.syncLegalRepresentative(request.companyId()); }
        @PostMapping("/internal/domain/FadadaCompanyOperations/sync1")
        public FadadaCompanyIdentityRespDTO sync1(@RequestBody Sync1Request request) { return operations.sync(request.companyId()); }
        @PostMapping("/internal/domain/FadadaCompanyOperations/syncByClientCorpId1")
        public FadadaCompanyIdentityRespDTO syncByClientCorpId1(@RequestBody SyncByClientCorpId1Request request) { return operations.syncByClientCorpId(request.clientCorpId()); }
        @PostMapping("/internal/domain/FadadaCompanyOperations/syncByOpenCorpId1")
        public FadadaCompanyIdentityRespDTO syncByOpenCorpId1(@RequestBody SyncByOpenCorpId1Request request) { return operations.syncByOpenCorpId(request.openCorpId()); }
        @PostMapping("/internal/domain/FadadaCompanyOperations/syncCallback3")
        public FadadaCompanyIdentityRespDTO syncCallback3(@RequestBody SyncCallback3Request request) { return operations.syncCallback(request.clientCorpId(), request.openCorpId(), request.data()); }
        @PostMapping("/internal/domain/FadadaCompanyOperations/createSealManageUrl1")
        public ServiceUrlPayload createSealManageUrl1(@RequestBody CreateSealManageUrl1Request request) { return operations.createSealManageUrl(request.companyId()); }
        @PostMapping("/internal/domain/FadadaCompanyOperations/requireVerified1")
        public FadadaCorpIdentityRespDTO requireVerified1(@RequestBody RequireVerified1Request request) { return operations.requireVerified(request.companyId()); }
        @PostMapping("/internal/domain/FadadaCompanyOperations/enabledSealId1")
        public String enabledSealId1(@RequestBody EnabledSealId1Request request) { return operations.enabledSealId(request.companyId()); }
    }
}
