package com.tradepass.framework.rpc.core;

// Generated by scripts/generate-domain-rpc.py from tradepass-module-identity/tradepass-module-identity-api/src/main/java/com/tradepass/module/identity/api/directory/IdentityDirectoryOperations.java.
import java.util.List;
import java.util.Map;
import com.tradepass.module.identity.api.directory.IdentityDirectoryOperations;
import com.tradepass.module.identity.api.directory.IdentityDirectoryOperations.*;
import com.tradepass.framework.rpc.config.DomainFeignConfiguration;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.context.annotation.*;
import org.springframework.boot.autoconfigure.condition.*;
import org.springframework.web.bind.annotation.*;

@Configuration(proxyBeanMethods = false)
@ConditionalOnProperty(name = "tradepass.services.split", havingValue = "true")
@Import(IdentityDirectoryOperationsHttp.Endpoint.class)
public class IdentityDirectoryOperationsHttp {
    public record CompanyNames1Request(List<Long> companyIds) {}
    public record CompanyIdsNamed1Request(String name) {}
    public record UserDisplayName1Request(long userId) {}
    public record UserNicknames1Request(List<Long> userIds) {}
    public record Counterparties1Request(long companyId) {}
    public record OrderedCompanyNames2Request(long companyAId, long companyBId) {}

    @FeignClient(name = "${tradepass.services.identity-name:tradepass-identity}", contextId = "IdentityDirectoryOperationsHttp",
            url = "${tradepass.services.identity-url:}", configuration = DomainFeignConfiguration.class)
    public interface Client {
        @PostMapping("/internal/domain/IdentityDirectoryOperations/companyNames1")
        Map<Long, String> companyNames1(@RequestBody CompanyNames1Request request);
        @PostMapping("/internal/domain/IdentityDirectoryOperations/companyIdsNamed1")
        List<Long> companyIdsNamed1(@RequestBody CompanyIdsNamed1Request request);
        @PostMapping("/internal/domain/IdentityDirectoryOperations/userDisplayName1")
        String userDisplayName1(@RequestBody UserDisplayName1Request request);
        @PostMapping("/internal/domain/IdentityDirectoryOperations/userNicknames1")
        Map<Long, String> userNicknames1(@RequestBody UserNicknames1Request request);
        @PostMapping("/internal/domain/IdentityDirectoryOperations/counterparties1")
        List<Counterparty> counterparties1(@RequestBody Counterparties1Request request);
        @PostMapping("/internal/domain/IdentityDirectoryOperations/orderedCompanyNames2")
        List<String> orderedCompanyNames2(@RequestBody OrderedCompanyNames2Request request);
    }

    @Bean
    @ConditionalOnExpression("!T(com.tradepass.framework.common.core.HostedRoles).hosts('${tradepass.runtime.role:}', 'identity')")
    IdentityDirectoryOperations remoteIdentityDirectoryOperations(Client client) {
        return new IdentityDirectoryOperations() {
            @Override public Map<Long, String> companyNames(List<Long> companyIds) { return client.companyNames1(new CompanyNames1Request(companyIds)); }
            @Override public List<Long> companyIdsNamed(String name) { return client.companyIdsNamed1(new CompanyIdsNamed1Request(name)); }
            @Override public String userDisplayName(long userId) { return client.userDisplayName1(new UserDisplayName1Request(userId)); }
            @Override public Map<Long, String> userNicknames(List<Long> userIds) { return client.userNicknames1(new UserNicknames1Request(userIds)); }
            @Override public List<Counterparty> counterparties(long companyId) { return client.counterparties1(new Counterparties1Request(companyId)); }
            @Override public List<String> orderedCompanyNames(long companyAId, long companyBId) { return client.orderedCompanyNames2(new OrderedCompanyNames2Request(companyAId, companyBId)); }
        };
    }

    @RestController
    @ConditionalOnExpression("T(com.tradepass.framework.common.core.HostedRoles).hosts('${tradepass.runtime.role:}', 'identity')")
    public static class Endpoint {
        private final IdentityDirectoryOperations operations;
        public Endpoint(IdentityDirectoryOperations operations) { this.operations = operations; }
        @PostMapping("/internal/domain/IdentityDirectoryOperations/companyNames1")
        public Map<Long, String> companyNames1(@RequestBody CompanyNames1Request request) { return operations.companyNames(request.companyIds()); }
        @PostMapping("/internal/domain/IdentityDirectoryOperations/companyIdsNamed1")
        public List<Long> companyIdsNamed1(@RequestBody CompanyIdsNamed1Request request) { return operations.companyIdsNamed(request.name()); }
        @PostMapping("/internal/domain/IdentityDirectoryOperations/userDisplayName1")
        public String userDisplayName1(@RequestBody UserDisplayName1Request request) { return operations.userDisplayName(request.userId()); }
        @PostMapping("/internal/domain/IdentityDirectoryOperations/userNicknames1")
        public Map<Long, String> userNicknames1(@RequestBody UserNicknames1Request request) { return operations.userNicknames(request.userIds()); }
        @PostMapping("/internal/domain/IdentityDirectoryOperations/counterparties1")
        public List<Counterparty> counterparties1(@RequestBody Counterparties1Request request) { return operations.counterparties(request.companyId()); }
        @PostMapping("/internal/domain/IdentityDirectoryOperations/orderedCompanyNames2")
        public List<String> orderedCompanyNames2(@RequestBody OrderedCompanyNames2Request request) { return operations.orderedCompanyNames(request.companyAId(), request.companyBId()); }
    }
}
