package com.tradepass.framework.rpc.core;

// Generated by scripts/generate-domain-rpc.py from tradepass-module-trade/tradepass-module-trade-api/src/main/java/com/tradepass/module/trade/api/ranking/RankingCacheOperations.java.
import com.tradepass.framework.common.pojo.TradePassDtos;
import com.tradepass.framework.common.pojo.TradePassDtos.RankingItem;
import java.util.List;
import com.tradepass.module.trade.api.ranking.RankingCacheOperations;
import com.tradepass.module.trade.api.ranking.RankingCacheOperations.*;
import com.tradepass.framework.rpc.config.DomainFeignConfiguration;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.context.annotation.*;
import org.springframework.boot.autoconfigure.condition.*;
import org.springframework.web.bind.annotation.*;

@Configuration(proxyBeanMethods = false)
@ConditionalOnProperty(name = "tradepass.services.split", havingValue = "true")
@Import(RankingCacheOperationsHttp.Endpoint.class)
public class RankingCacheOperationsHttp {
    public record Get3Request(long companyId, String direction, String period) {}
    public record Put4Request(long companyId, String direction, String period, List<RankingItem> ranking) {}
    public record Evict2Request(long companyId, String direction) {}

    @FeignClient(name = "tradepass-trade", contextId = "RankingCacheOperationsHttp",
            url = "${tradepass.services.trade-url:}", configuration = DomainFeignConfiguration.class)
    public interface Client {
        @PostMapping("/internal/domain/RankingCacheOperations/get3")
        List<RankingItem> get3(@RequestBody Get3Request request);
        @PostMapping("/internal/domain/RankingCacheOperations/put4")
        void put4(@RequestBody Put4Request request);
        @PostMapping("/internal/domain/RankingCacheOperations/evict2")
        void evict2(@RequestBody Evict2Request request);
    }

    @Bean
    @ConditionalOnExpression("'${tradepass.runtime.role:}' != 'trade'")
    RankingCacheOperations remoteRankingCacheOperations(Client client) {
        return new RankingCacheOperations() {
            @Override public List<RankingItem> get(long companyId, String direction, String period) { return client.get3(new Get3Request(companyId, direction, period)); }
            @Override public void put(long companyId, String direction, String period, List<RankingItem> ranking) { client.put4(new Put4Request(companyId, direction, period, ranking)); }
            @Override public void evict(long companyId, String direction) { client.evict2(new Evict2Request(companyId, direction)); }
        };
    }

    @RestController
    @ConditionalOnProperty(name = "tradepass.runtime.role", havingValue = "trade")
    public static class Endpoint {
        private final RankingCacheOperations operations;
        public Endpoint(RankingCacheOperations operations) { this.operations = operations; }
        @PostMapping("/internal/domain/RankingCacheOperations/get3")
        public List<RankingItem> get3(@RequestBody Get3Request request) { return operations.get(request.companyId(), request.direction(), request.period()); }
        @PostMapping("/internal/domain/RankingCacheOperations/put4")
        public void put4(@RequestBody Put4Request request) { operations.put(request.companyId(), request.direction(), request.period(), request.ranking()); }
        @PostMapping("/internal/domain/RankingCacheOperations/evict2")
        public void evict2(@RequestBody Evict2Request request) { operations.evict(request.companyId(), request.direction()); }
    }
}
