package com.tradepass.framework.rpc.core;

// Generated by scripts/generate-domain-rpc.py from tradepass-module-settlement/tradepass-module-settlement-api/src/main/java/com/tradepass/module/settlement/api/reconciliation/ReconciliationAccountOperations.java.
import com.tradepass.module.trade.api.document.dto.BusinessDocumentRespDTO;
import com.tradepass.module.contract.api.contract.dto.TradeContractRespDTO;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;
import com.tradepass.module.settlement.api.reconciliation.ReconciliationAccountOperations;
import com.tradepass.module.settlement.api.reconciliation.ReconciliationAccountOperations.*;
import com.tradepass.framework.rpc.config.DomainFeignConfiguration;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.context.annotation.*;
import org.springframework.boot.autoconfigure.condition.*;
import org.springframework.web.bind.annotation.*;

@Configuration(proxyBeanMethods = false)
@ConditionalOnProperty(name = "tradepass.services.split", havingValue = "true")
@Import(ReconciliationAccountOperationsHttp.Endpoint.class)
public class ReconciliationAccountOperationsHttp {
    public record ListAccounts0Request() {}
    public record ListAccounts1Request(String role) {}
    public record Account1Request(Long counterpartyCompanyId) {}
    public record Account2Request(Long counterpartyCompanyId, String role) {}
    public record Workbook1Request(Long counterpartyCompanyId) {}
    public record RecordSalesOrder5Request(BusinessDocumentRespDTO document, BigDecimal amount, LocalDate businessDate, long approvedBy, LocalDateTime approvedAt) {}
    public record RecordReturnOrder5Request(BusinessDocumentRespDTO document, BigDecimal amount, LocalDate businessDate, long approvedBy, LocalDateTime approvedAt) {}
    public record RecordAttachment9Request(TradeContractRespDTO contract, String sourceType, long sourceId, LocalDate businessDate, String documentNo, BigDecimal amount, long issuerCompanyId, long approvedBy, LocalDateTime approvedAt) {}
    public record ReverseSource5Request(String sourceType, long sourceId, long actionRequestId, long approvedBy, LocalDateTime approvedAt) {}

    @FeignClient(name = "tradepass-settlement", contextId = "ReconciliationAccountOperationsHttp",
            url = "${tradepass.services.settlement-url:}", configuration = DomainFeignConfiguration.class)
    public interface Client {
        @PostMapping("/internal/domain/ReconciliationAccountOperations/listAccounts0")
        List<Map<String, Object>> listAccounts0(@RequestBody ListAccounts0Request request);
        @PostMapping("/internal/domain/ReconciliationAccountOperations/listAccounts1")
        List<Map<String, Object>> listAccounts1(@RequestBody ListAccounts1Request request);
        @PostMapping("/internal/domain/ReconciliationAccountOperations/account1")
        Map<String, Object> account1(@RequestBody Account1Request request);
        @PostMapping("/internal/domain/ReconciliationAccountOperations/account2")
        Map<String, Object> account2(@RequestBody Account2Request request);
        @PostMapping("/internal/domain/ReconciliationAccountOperations/workbook1")
        WorkbookRespDTO workbook1(@RequestBody Workbook1Request request);
        @PostMapping("/internal/domain/ReconciliationAccountOperations/recordSalesOrder5")
        void recordSalesOrder5(@RequestBody RecordSalesOrder5Request request);
        @PostMapping("/internal/domain/ReconciliationAccountOperations/recordReturnOrder5")
        void recordReturnOrder5(@RequestBody RecordReturnOrder5Request request);
        @PostMapping("/internal/domain/ReconciliationAccountOperations/recordAttachment9")
        void recordAttachment9(@RequestBody RecordAttachment9Request request);
        @PostMapping("/internal/domain/ReconciliationAccountOperations/reverseSource5")
        void reverseSource5(@RequestBody ReverseSource5Request request);
    }

    @Bean
    @ConditionalOnExpression("'${tradepass.runtime.role:}' != 'settlement'")
    ReconciliationAccountOperations remoteReconciliationAccountOperations(Client client) {
        return new ReconciliationAccountOperations() {
            @Override public List<Map<String, Object>> listAccounts() { return client.listAccounts0(new ListAccounts0Request()); }
            @Override public List<Map<String, Object>> listAccounts(String role) { return client.listAccounts1(new ListAccounts1Request(role)); }
            @Override public Map<String, Object> account(Long counterpartyCompanyId) { return client.account1(new Account1Request(counterpartyCompanyId)); }
            @Override public Map<String, Object> account(Long counterpartyCompanyId, String role) { return client.account2(new Account2Request(counterpartyCompanyId, role)); }
            @Override public WorkbookRespDTO workbook(Long counterpartyCompanyId) { return client.workbook1(new Workbook1Request(counterpartyCompanyId)); }
            @Override public void recordSalesOrder(BusinessDocumentRespDTO document, BigDecimal amount, LocalDate businessDate, long approvedBy, LocalDateTime approvedAt) { client.recordSalesOrder5(new RecordSalesOrder5Request(document, amount, businessDate, approvedBy, approvedAt)); }
            @Override public void recordReturnOrder(BusinessDocumentRespDTO document, BigDecimal amount, LocalDate businessDate, long approvedBy, LocalDateTime approvedAt) { client.recordReturnOrder5(new RecordReturnOrder5Request(document, amount, businessDate, approvedBy, approvedAt)); }
            @Override public void recordAttachment(TradeContractRespDTO contract, String sourceType, long sourceId, LocalDate businessDate, String documentNo, BigDecimal amount, long issuerCompanyId, long approvedBy, LocalDateTime approvedAt) { client.recordAttachment9(new RecordAttachment9Request(contract, sourceType, sourceId, businessDate, documentNo, amount, issuerCompanyId, approvedBy, approvedAt)); }
            @Override public void reverseSource(String sourceType, long sourceId, long actionRequestId, long approvedBy, LocalDateTime approvedAt) { client.reverseSource5(new ReverseSource5Request(sourceType, sourceId, actionRequestId, approvedBy, approvedAt)); }
        };
    }

    @RestController
    @ConditionalOnProperty(name = "tradepass.runtime.role", havingValue = "settlement")
    public static class Endpoint {
        private final ReconciliationAccountOperations operations;
        public Endpoint(ReconciliationAccountOperations operations) { this.operations = operations; }
        @PostMapping("/internal/domain/ReconciliationAccountOperations/listAccounts0")
        public List<Map<String, Object>> listAccounts0(@RequestBody ListAccounts0Request request) { return operations.listAccounts(); }
        @PostMapping("/internal/domain/ReconciliationAccountOperations/listAccounts1")
        public List<Map<String, Object>> listAccounts1(@RequestBody ListAccounts1Request request) { return operations.listAccounts(request.role()); }
        @PostMapping("/internal/domain/ReconciliationAccountOperations/account1")
        public Map<String, Object> account1(@RequestBody Account1Request request) { return operations.account(request.counterpartyCompanyId()); }
        @PostMapping("/internal/domain/ReconciliationAccountOperations/account2")
        public Map<String, Object> account2(@RequestBody Account2Request request) { return operations.account(request.counterpartyCompanyId(), request.role()); }
        @PostMapping("/internal/domain/ReconciliationAccountOperations/workbook1")
        public WorkbookRespDTO workbook1(@RequestBody Workbook1Request request) { return operations.workbook(request.counterpartyCompanyId()); }
        @PostMapping("/internal/domain/ReconciliationAccountOperations/recordSalesOrder5")
        public void recordSalesOrder5(@RequestBody RecordSalesOrder5Request request) { operations.recordSalesOrder(request.document(), request.amount(), request.businessDate(), request.approvedBy(), request.approvedAt()); }
        @PostMapping("/internal/domain/ReconciliationAccountOperations/recordReturnOrder5")
        public void recordReturnOrder5(@RequestBody RecordReturnOrder5Request request) { operations.recordReturnOrder(request.document(), request.amount(), request.businessDate(), request.approvedBy(), request.approvedAt()); }
        @PostMapping("/internal/domain/ReconciliationAccountOperations/recordAttachment9")
        public void recordAttachment9(@RequestBody RecordAttachment9Request request) { operations.recordAttachment(request.contract(), request.sourceType(), request.sourceId(), request.businessDate(), request.documentNo(), request.amount(), request.issuerCompanyId(), request.approvedBy(), request.approvedAt()); }
        @PostMapping("/internal/domain/ReconciliationAccountOperations/reverseSource5")
        public void reverseSource5(@RequestBody ReverseSource5Request request) { operations.reverseSource(request.sourceType(), request.sourceId(), request.actionRequestId(), request.approvedBy(), request.approvedAt()); }
    }
}
