package com.tradepass.framework.rpc.core;

// Generated by scripts/generate-domain-rpc.py from tradepass-module-settlement/tradepass-module-settlement-api/src/main/java/com/tradepass/module/settlement/api/reconciliation/ReconciliationStatementOperations.java.
import com.tradepass.framework.common.util.FileTypeInspector;
import java.util.List;
import java.util.Map;
import com.tradepass.module.settlement.api.reconciliation.ReconciliationStatementOperations;
import com.tradepass.module.settlement.api.reconciliation.ReconciliationStatementOperations.*;
import com.tradepass.framework.rpc.config.DomainFeignConfiguration;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.context.annotation.*;
import org.springframework.boot.autoconfigure.condition.*;
import org.springframework.web.bind.annotation.*;

@Configuration(proxyBeanMethods = false)
@ConditionalOnProperty(name = "tradepass.services.split", havingValue = "true")
@Import(ReconciliationStatementOperationsHttp.Endpoint.class)
public class ReconciliationStatementOperationsHttp {
    public record List1Request(Long counterpartyCompanyId) {}
    public record Upload5Request(Long counterpartyCompanyId, String period, String remark, String originalName, byte[] data) {}
    public record GetFile1Request(Long id) {}

    @FeignClient(name = "${tradepass.services.settlement-name:tradepass-settlement}", contextId = "ReconciliationStatementOperationsHttp",
            url = "${tradepass.services.settlement-url:}", configuration = DomainFeignConfiguration.class)
    public interface Client {
        @PostMapping("/internal/domain/ReconciliationStatementOperations/list1")
        List<Map<String, Object>> list1(@RequestBody List1Request request);
        @PostMapping("/internal/domain/ReconciliationStatementOperations/upload5")
        Map<String, Object> upload5(@RequestBody Upload5Request request);
        @PostMapping("/internal/domain/ReconciliationStatementOperations/getFile1")
        FileRespDTO getFile1(@RequestBody GetFile1Request request);
    }

    @Bean
    @ConditionalOnExpression("!T(com.tradepass.framework.common.core.HostedRoles).hosts('${tradepass.runtime.role:}', 'settlement')")
    ReconciliationStatementOperations remoteReconciliationStatementOperations(Client client) {
        return new ReconciliationStatementOperations() {
            @Override public List<Map<String, Object>> list(Long counterpartyCompanyId) { return client.list1(new List1Request(counterpartyCompanyId)); }
            @Override public Map<String, Object> upload(Long counterpartyCompanyId, String period, String remark, String originalName, byte[] data) { return client.upload5(new Upload5Request(counterpartyCompanyId, period, remark, originalName, data)); }
            @Override public FileRespDTO getFile(Long id) { return client.getFile1(new GetFile1Request(id)); }
        };
    }

    @RestController
    @ConditionalOnExpression("T(com.tradepass.framework.common.core.HostedRoles).hosts('${tradepass.runtime.role:}', 'settlement')")
    public static class Endpoint {
        private final ReconciliationStatementOperations operations;
        public Endpoint(ReconciliationStatementOperations operations) { this.operations = operations; }
        @PostMapping("/internal/domain/ReconciliationStatementOperations/list1")
        public List<Map<String, Object>> list1(@RequestBody List1Request request) { return operations.list(request.counterpartyCompanyId()); }
        @PostMapping("/internal/domain/ReconciliationStatementOperations/upload5")
        public Map<String, Object> upload5(@RequestBody Upload5Request request) { return operations.upload(request.counterpartyCompanyId(), request.period(), request.remark(), request.originalName(), request.data()); }
        @PostMapping("/internal/domain/ReconciliationStatementOperations/getFile1")
        public FileRespDTO getFile1(@RequestBody GetFile1Request request) { return operations.getFile(request.id()); }
    }
}
