package com.tradepass.framework.rpc.core;

// Generated by scripts/generate-domain-rpc.py from tradepass-module-trade/tradepass-module-trade-api/src/main/java/com/tradepass/module/trade/api/ranking/SalesPerformanceOperations.java.
import java.math.BigDecimal;
import java.util.Map;
import com.tradepass.module.trade.api.ranking.SalesPerformanceOperations;
import com.tradepass.module.trade.api.ranking.SalesPerformanceOperations.*;
import com.tradepass.framework.rpc.config.DomainFeignConfiguration;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.context.annotation.*;
import org.springframework.boot.autoconfigure.condition.*;
import org.springframework.web.bind.annotation.*;

@Configuration(proxyBeanMethods = false)
@ConditionalOnProperty(name = "tradepass.services.split", havingValue = "true")
@Import(SalesPerformanceOperationsHttp.Endpoint.class)
public class SalesPerformanceOperationsHttp {
    public record ContractSales1Request(long companyId) {}

    @FeignClient(name = "${tradepass.services.trade-name:tradepass-trade}", contextId = "SalesPerformanceOperationsHttp",
            url = "${tradepass.services.trade-url:}", configuration = DomainFeignConfiguration.class)
    public interface Client {
        @PostMapping("/internal/domain/SalesPerformanceOperations/contractSales1")
        Map<String, ContractSales> contractSales1(@RequestBody ContractSales1Request request);
    }

    @Bean
    @ConditionalOnExpression("!T(com.tradepass.framework.common.core.HostedRoles).hosts('${tradepass.runtime.role:}', 'trade')")
    SalesPerformanceOperations remoteSalesPerformanceOperations(Client client) {
        return new SalesPerformanceOperations() {
            @Override public Map<String, ContractSales> contractSales(long companyId) { return client.contractSales1(new ContractSales1Request(companyId)); }
        };
    }

    @RestController
    @ConditionalOnExpression("T(com.tradepass.framework.common.core.HostedRoles).hosts('${tradepass.runtime.role:}', 'trade')")
    public static class Endpoint {
        private final SalesPerformanceOperations operations;
        public Endpoint(SalesPerformanceOperations operations) { this.operations = operations; }
        @PostMapping("/internal/domain/SalesPerformanceOperations/contractSales1")
        public Map<String, ContractSales> contractSales1(@RequestBody ContractSales1Request request) { return operations.contractSales(request.companyId()); }
    }
}
