package com.tradepass.framework.rpc.core;

// Generated by scripts/generate-domain-rpc.py from tradepass-module-identity/tradepass-module-identity-api/src/main/java/com/tradepass/module/identity/api/user/UserIdentityOperations.java.

import com.tradepass.module.identity.api.user.UserIdentityOperations;
import com.tradepass.module.identity.api.user.UserIdentityOperations.*;
import com.tradepass.framework.rpc.config.DomainFeignConfiguration;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.context.annotation.*;
import org.springframework.boot.autoconfigure.condition.*;
import org.springframework.web.bind.annotation.*;

@Configuration(proxyBeanMethods = false)
@ConditionalOnProperty(name = "tradepass.services.split", havingValue = "true")
@Import(UserIdentityOperationsHttp.Endpoint.class)
public class UserIdentityOperationsHttp {
    public record CurrentDisplayName0Request() {}
    public record RequireCurrentVerifiedName1Request(long companyId) {}

    @FeignClient(name = "${tradepass.services.identity-name:tradepass-identity}", contextId = "UserIdentityOperationsHttp",
            url = "${tradepass.services.identity-url:}", configuration = DomainFeignConfiguration.class)
    public interface Client {
        @PostMapping("/internal/domain/UserIdentityOperations/currentDisplayName0")
        String currentDisplayName0(@RequestBody CurrentDisplayName0Request request);
        @PostMapping("/internal/domain/UserIdentityOperations/requireCurrentVerifiedName1")
        String requireCurrentVerifiedName1(@RequestBody RequireCurrentVerifiedName1Request request);
    }

    @Bean
    @ConditionalOnExpression("!T(com.tradepass.framework.common.core.HostedRoles).hosts('${tradepass.runtime.role:}', 'identity')")
    UserIdentityOperations remoteUserIdentityOperations(Client client) {
        return new UserIdentityOperations() {
            @Override public String currentDisplayName() { return client.currentDisplayName0(new CurrentDisplayName0Request()); }
            @Override public String requireCurrentVerifiedName(long companyId) { return client.requireCurrentVerifiedName1(new RequireCurrentVerifiedName1Request(companyId)); }
        };
    }

    @RestController
    @ConditionalOnExpression("T(com.tradepass.framework.common.core.HostedRoles).hosts('${tradepass.runtime.role:}', 'identity')")
    public static class Endpoint {
        private final UserIdentityOperations operations;
        public Endpoint(UserIdentityOperations operations) { this.operations = operations; }
        @PostMapping("/internal/domain/UserIdentityOperations/currentDisplayName0")
        public String currentDisplayName0(@RequestBody CurrentDisplayName0Request request) { return operations.currentDisplayName(); }
        @PostMapping("/internal/domain/UserIdentityOperations/requireCurrentVerifiedName1")
        public String requireCurrentVerifiedName1(@RequestBody RequireCurrentVerifiedName1Request request) { return operations.requireCurrentVerifiedName(request.companyId()); }
    }
}
