<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.tradepass</groupId>
    <artifactId>tradepass-module-trade</artifactId>
    <version>0.1.0-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>
  <artifactId>tradepass-module-trade-server</artifactId>
  <packaging>jar</packaging>
  <dependencies>
    <dependency>
      <groupId>com.tradepass</groupId>
      <artifactId>tradepass-spring-boot-starter-rpc</artifactId>
    </dependency>
    <dependency>
      <groupId>com.tradepass</groupId>
      <artifactId>tradepass-spring-boot-starter-service</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.tradepass</groupId>
      <artifactId>tradepass-common</artifactId>
      <type>test-jar</type>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.tradepass</groupId>
      <artifactId>tradepass-spring-boot-starter-core</artifactId>
    </dependency>
    <dependency>
      <groupId>com.tradepass</groupId>
      <artifactId>tradepass-module-trade-api</artifactId>
    </dependency>
    <dependency>
      <groupId>com.tradepass</groupId>
      <artifactId>tradepass-module-identity-api</artifactId>
    </dependency>
    <dependency>
      <groupId>com.tradepass</groupId>
      <artifactId>tradepass-module-contract-api</artifactId>
    </dependency>
    <dependency>
      <groupId>com.tradepass</groupId>
      <artifactId>tradepass-module-settlement-api</artifactId>
    </dependency>
    <dependency>
      <groupId>com.tradepass</groupId>
      <artifactId>tradepass-module-file-api</artifactId>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <executions>
          <execution>
            <id>app-classes</id>
            <phase>process-classes</phase>
            <goals>
              <goal>jar</goal>
            </goals>
            <configuration>
              <classifier>classes</classifier>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <configuration>
          <mainClass>com.tradepass.module.trade.TradeServerApplication</mainClass>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>