<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.tradepass</groupId>
    <artifactId>tradepass-parent</artifactId>
    <version>0.1.0-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>
  <artifactId>tradepass-gateway</artifactId>
  <dependencies>
    <dependency>
      <groupId>net.logstash.logback</groupId>
      <artifactId>logstash-logback-encoder</artifactId>
    </dependency>
    <dependency>
      <groupId>com.tradepass</groupId>
      <artifactId>tradepass-spring-boot-starter-governance</artifactId>
    </dependency>
    <dependency>
      <groupId>com.alibaba.csp</groupId>
      <artifactId>sentinel-spring-cloud-gateway-adapter</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-gateway</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-actuator</artifactId>
    </dependency>
    <dependency>
      <groupId>io.micrometer</groupId>
      <artifactId>micrometer-registry-prometheus</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.tradepass</groupId>
      <artifactId>tradepass-spring-boot-starter-service</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.tradepass</groupId>
      <artifactId>tradepass-module-identity-server</artifactId>
      <scope>test</scope>
      <classifier>classes</classifier>
    </dependency>
    <dependency>
      <groupId>com.tradepass</groupId>
      <artifactId>tradepass-module-contract-server</artifactId>
      <scope>test</scope>
      <classifier>classes</classifier>
    </dependency>
    <dependency>
      <groupId>com.tradepass</groupId>
      <artifactId>tradepass-module-trade-server</artifactId>
      <scope>test</scope>
      <classifier>classes</classifier>
    </dependency>
    <dependency>
      <groupId>com.tradepass</groupId>
      <artifactId>tradepass-module-settlement-server</artifactId>
      <scope>test</scope>
      <classifier>classes</classifier>
    </dependency>
    <dependency>
      <groupId>com.tradepass</groupId>
      <artifactId>tradepass-module-file-server</artifactId>
      <scope>test</scope>
      <classifier>classes</classifier>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
      </plugin>
    </plugins>
  </build>
</project>