server:
  port: 7091
spring:
  application:
    name: seata-server
logging:
  config: classpath:logback-spring.xml
  file:
    path: /seata-server/logs
console:
  user:
    username: ${SEATA_CONSOLE_USERNAME}
    password: ${SEATA_CONSOLE_PASSWORD}
seata:
  config:
    type: file
  registry:
    type: file
  store:
    mode: file
    file:
      dir: /seata-server/sessionStore
  server:
    service-port: 8091
  security:
    secretKey: ${SEATA_SECURITY_SECRET_KEY}
    tokenValidityInMilliseconds: 1800000
    ignore:
      urls: /,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.jpeg,/**/*.ico,/api/v1/auth/login,/version.json,/health,/error
