<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.tradepass</groupId>
    <artifactId>tradepass-parent</artifactId>
    <version>0.1.0-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>
  <artifactId>tradepass-module-settlement</artifactId>
  <packaging>pom</packaging>
  <modules>
    <module>tradepass-module-settlement-api</module>
    <module>tradepass-module-settlement-server</module>
  </modules>
</project>