tradepass:
  services:
    identity-url: lb://tradepass-identity
    contract-url: lb://${tradepass.services.contract-name:tradepass-contract}
    trade-url: lb://${tradepass.services.trade-name:tradepass-trade}
    settlement-url: lb://${tradepass.services.settlement-name:tradepass-settlement}
    file-url: lb://${tradepass.services.file-name:tradepass-file}
