package com.tradepass.module.contract.service.contract;

import com.tradepass.module.contract.service.archive.ContractArchiveService;
import com.tradepass.module.contract.service.directory.ContractDirectoryService;
import com.tradepass.module.contract.service.signing.ContractSigningCancellationService;
import com.tradepass.module.identity.api.directory.IdentityDirectoryOperations;
import com.tradepass.module.identity.api.directory.IdentityDirectoryOperations.*;
import com.tradepass.module.identity.api.permission.AccessControlOperations;
import com.tradepass.module.identity.api.permission.AccessControlOperations.*;
import com.tradepass.framework.audit.core.AuditLogService;
import com.tradepass.module.trade.api.approval.ApprovalOperations;
import com.tradepass.module.trade.api.approval.ApprovalOperations.*;
import com.tradepass.module.trade.api.ranking.RankingCacheOperations;
import com.tradepass.module.trade.api.ranking.RankingCacheOperations.*;
import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.baomidou.mybatisplus.core.conditions.update.LambdaUpdateWrapper;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.tradepass.framework.common.core.AuthContext;
import com.tradepass.framework.common.exception.BusinessException;
import com.tradepass.module.contract.controller.app.contract.vo.CreateContractReqVO;
import com.tradepass.module.contract.api.contract.dto.ContractRespDTO;
import com.tradepass.framework.common.pojo.PagePayload;
import com.tradepass.module.identity.api.company.dto.CompanyRespDTO;
import com.tradepass.module.contract.dal.dataobject.template.ContractTemplateDO;
import com.tradepass.module.contract.dal.dataobject.template.TemplateCategoryDO;
import com.tradepass.module.contract.dal.dataobject.contract.TradeContractDO;
import com.tradepass.module.identity.api.company.CompanyReader;
import com.tradepass.module.identity.api.company.CompanyReader.*;
import com.tradepass.module.contract.dal.mysql.template.ContractTemplateMapper;
import com.tradepass.module.identity.api.counterparty.CounterpartyReader;
import com.tradepass.module.identity.api.counterparty.CounterpartyReader.*;
import com.tradepass.module.contract.dal.mysql.template.TemplateCategoryMapper;
import com.tradepass.module.contract.dal.mysql.contract.TradeContractMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.dao.DuplicateKeyException;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;
import java.util.UUID;

public interface TradeService {
    void setApprovalService(ApprovalOperations approvalService);
    void setSigningCancellation(ContractSigningCancellationService signingCancellation);
    List<Map<String, Object>> listTemplateCategories();
    Map<String, Object> addCategory(Map<String, Object> body);
    String deleteCategory(Long id);
    List<Map<String, Object>> listTemplates(String keyword, String category);
    PagePayload<Map<String, Object>> pageTemplates(String keyword, String category, int page, int size);
    Map<String, Object> getTemplate(Long id);
    Map<String, Object> createTemplate(Map<String, Object> body);
    Map<String, Object> updateTemplate(Long id, Map<String, Object> body);
    String deleteTemplate(Long id);
    ContractRespDTO getContract(Long id);
    ContractRespDTO contractForElectronicSignature(Long id, long viewerCompanyId);
    void activateAfterElectronicSignature(Long id, int expectedVersion, long completedBy);
    void voidAfterElectronicAbolish(Long id, int expectedVersion, long completedBy);
    List<ContractRespDTO> listContracts(String counterpartyName);
    PagePayload<ContractRespDTO> pageContracts(String counterpartyName, String status, int page, int size);
    Map<String, Object> contractSummary();
    ContractRespDTO createContract(CreateContractReqVO request);
    String approveContract(Long id);
    String rejectContract(Long id);
    String cancelContract(Long id);
    ContractRespDTO resubmitContract(Long id, CreateContractReqVO request);
    String deleteContract(Long id);
    List<ContractRespDTO> myInitiatedContracts();
    List<ContractRespDTO> pendingContracts();
}
