#!/usr/bin/env python3
"""Deliver only core release metadata/images and publisher over verified SSH."""
import argparse
import json
from pathlib import Path
import re
import shlex
import subprocess
import tarfile
import tempfile
import uuid

ROOT = Path(__file__).resolve().parents[2]


def ssh_command(host, user, port, known_hosts, identity_file=None):
    if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9.-]*", host):
        raise ValueError("无效 SSH 主机名")
    if not re.fullmatch(r"[a-z_][a-z0-9_-]*", user) or not 1 <= port <= 65535:
        raise ValueError("无效 SSH 账号或端口")
    if not known_hosts.is_file():
        raise ValueError("需要已核验的 SSH known_hosts 文件凭据")
    identity_options = []
    if identity_file is not None:
        if not identity_file.is_file():
            raise ValueError("SSH 私钥文件不存在")
        identity_options = ["-i", str(identity_file.resolve()), "-o", "IdentitiesOnly=yes", "-o", "IdentityAgent=none"]
    return ["ssh", "-p", str(port), *identity_options, "-o", "BatchMode=yes", "-o", "StrictHostKeyChecking=yes",
            "-o", "ConnectTimeout=15", "-o", "ServerAliveInterval=15", "-o", "ServerAliveCountMax=4",
            "-o", "UserKnownHostsFile=" + str(known_hosts.resolve()), user + "@" + host]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("action", choices=["deploy", "status", "restart", "rollback", "recover"])
    parser.add_argument("--service", choices=["identity", "business", "gateway", "all"], required=True)
    parser.add_argument("--host", required=True)
    parser.add_argument("--user", default="root")
    parser.add_argument("--port", type=int, default=22)
    parser.add_argument("--known-hosts", type=Path, required=True)
    parser.add_argument("--identity-file", type=Path)
    parser.add_argument("--compose", default="")
    parser.add_argument("--bundle", type=Path, default=ROOT / "dist/core-release")
    args = parser.parse_args()
    ssh = ssh_command(args.host, args.user, args.port, args.known_hosts, args.identity_file)
    if args.compose and (not args.compose.startswith("/") or "\n" in args.compose):
        parser.error("CORE_COMPOSE 必须是绝对路径")
    staging = "/var/tmp/tradepass-core-release-" + uuid.uuid4().hex
    files = [(ROOT / "scripts/cd/core_apply.py", "core_apply.py")]
    if args.action == "deploy":
        manifest = json.loads((args.bundle / "release.json").read_text())
        files.append((args.bundle / "release.json", "release.json"))
        if manifest.get("delivery") == "archive":
            files.append((args.bundle / "images.tar", "images.tar"))
    try:
        with tempfile.TemporaryFile() as archive:
            with tarfile.open(fileobj=archive, mode="w") as tar:
                for source, name in files:
                    if source.is_symlink() or not source.is_file():
                        raise ValueError("发布文件缺失：" + name)
                    tar.add(source, arcname=name, recursive=False)
            archive.seek(0)
            command = "umask 077; mkdir " + shlex.quote(staging) + " && tar -xf - --no-same-owner -C " + shlex.quote(staging)
            subprocess.run(ssh + [command], stdin=archive, check=True)
        command = ["python3", staging + "/core_apply.py", args.action, "--service", args.service,
                   "--bundle", staging]
        if args.compose:
            command += ["--compose", args.compose]
        subprocess.run(ssh + [shlex.join(command)], check=True)
    finally:
        # Delete only the staging directory generated by this invocation, never runtime data.
        subprocess.run(ssh + ["rm -rf -- " + shlex.quote(staging)], check=False)


if __name__ == "__main__":
    main()
