package com.tradepass.framework.rpc.config;

// Generated by scripts/generate-domain-rpc.py.
import com.tradepass.framework.rpc.core.*;
import org.springframework.context.annotation.*;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.cloud.openfeign.EnableFeignClients;

@Configuration(proxyBeanMethods = false)
@ConditionalOnProperty(name = "tradepass.services.split", havingValue = "true")
@Import({IdentityDirectoryOperationsHttp.class, FadadaCompanyOperationsHttp.class, FadadaPersonalIdentityOperationsHttp.class, AccessControlOperationsHttp.class, UserIdentityOperationsHttp.class, CompanyReaderHttp.class, CounterpartyReaderHttp.class, ContractAbolishRecoveryOperationsHttp.class, ContractDirectoryOperationsHttp.class, FadadaContractSigningOperationsHttp.class, ContractStateOperationsHttp.class, ContractTenantOperationsHttp.class, ContractReaderHttp.class, ApprovalOperationsHttp.class, BilateralActionOperationsHttp.class, BilateralStateOperationsHttp.class, BusinessDocumentOperationsHttp.class, DocumentTenantOperationsHttp.class, RankingCacheOperationsHttp.class, DocumentTodoReaderHttp.class, AttachmentApprovalOperationsHttp.class, AttachmentStateOperationsHttp.class, ContractAttachmentOperationsHttp.class, ReconciliationAccountOperationsHttp.class, ReconciliationStatementOperationsHttp.class})
@EnableFeignClients(clients = {IdentityDirectoryOperationsHttp.Client.class, FadadaCompanyOperationsHttp.Client.class, FadadaPersonalIdentityOperationsHttp.Client.class, AccessControlOperationsHttp.Client.class, UserIdentityOperationsHttp.Client.class, CompanyReaderHttp.Client.class, CounterpartyReaderHttp.Client.class, ContractAbolishRecoveryOperationsHttp.Client.class, ContractDirectoryOperationsHttp.Client.class, FadadaContractSigningOperationsHttp.Client.class, ContractStateOperationsHttp.Client.class, ContractTenantOperationsHttp.Client.class, ContractReaderHttp.Client.class, ApprovalOperationsHttp.Client.class, BilateralActionOperationsHttp.Client.class, BilateralStateOperationsHttp.Client.class, BusinessDocumentOperationsHttp.Client.class, DocumentTenantOperationsHttp.Client.class, RankingCacheOperationsHttp.Client.class, DocumentTodoReaderHttp.Client.class, AttachmentApprovalOperationsHttp.Client.class, AttachmentStateOperationsHttp.Client.class, ContractAttachmentOperationsHttp.Client.class, ReconciliationAccountOperationsHttp.Client.class, ReconciliationStatementOperationsHttp.Client.class})
public class DomainRpcConfiguration { }
