package com.tradepass.module.identity.service.auth;

import com.tradepass.framework.common.pojo.TradePassDtos;
import com.tradepass.module.identity.dal.dataobject.permission.PermDefDO;
import com.tradepass.module.identity.service.permission.AccessControlService;
import com.tradepass.module.identity.service.permission.RolePermissionService;
import com.tradepass.module.trade.api.document.BusinessDocumentOperations;
import com.tradepass.module.trade.api.document.BusinessDocumentOperations.*;
import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.baomidou.mybatisplus.core.conditions.update.LambdaUpdateWrapper;
import com.tradepass.framework.common.core.AuthContext;
import com.tradepass.framework.common.exception.BusinessException;
import com.tradepass.framework.common.pojo.TradePassDtos.CompanyProfile;
import com.tradepass.framework.common.pojo.TradePassDtos.CompanyRole;
import com.tradepass.framework.common.pojo.TradePassDtos.DevUser;
import com.tradepass.framework.common.pojo.TradePassDtos.LoginSession;
import com.tradepass.framework.common.pojo.TradePassDtos.MePayload;
import com.tradepass.framework.common.pojo.TradePassDtos.MemberInfo;
import com.tradepass.framework.common.pojo.TradePassDtos.UserProfile;
import com.tradepass.module.identity.controller.app.auth.vo.BindCompanyReqVO;
import com.tradepass.module.identity.controller.app.auth.vo.BindPhoneReqVO;
import com.tradepass.module.identity.controller.app.auth.vo.SwitchCompanyReqVO;
import com.tradepass.module.identity.controller.app.auth.vo.SwitchUserReqVO;
import com.tradepass.module.identity.controller.app.auth.vo.WechatLoginReqVO;
import com.tradepass.module.trade.api.document.dto.TodoItem;
import com.tradepass.module.identity.dal.dataobject.company.CompanyDO;
import com.tradepass.module.identity.dal.dataobject.company.CompanyMemberDO;
import com.tradepass.module.trade.api.document.dto.BusinessDocumentRespDTO;
import com.tradepass.module.identity.dal.dataobject.user.SysUserDO;
import com.tradepass.module.identity.dal.mysql.company.CompanyMapper;
import com.tradepass.module.identity.dal.mysql.company.CompanyMemberMapper;
import com.tradepass.module.trade.api.document.DocumentTodoReader;
import com.tradepass.module.trade.api.document.DocumentTodoReader.*;
import com.tradepass.module.identity.dal.mysql.permission.PermDefMapper;
import com.tradepass.module.identity.dal.mysql.user.SysUserMapper;
import com.tradepass.module.contract.api.contract.ContractReader;
import com.tradepass.module.contract.api.contract.ContractReader.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.transaction.annotation.Isolation;
import org.springframework.beans.factory.annotation.Value;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

public interface AuthService {
    LoginSession wechatLogin(WechatLoginReqVO request);
    LoginSession wechatLogin(WechatLoginReqVO request, String trustedOpenid);
    UserProfile bindPhone(BindPhoneReqVO request);
    MePayload me();
    List<Map<String, Object>> permissions();
    List<TodoItem> myTodos();
    MePayload switchCompany(SwitchCompanyReqVO request);
    MePayload bindCompany(BindCompanyReqVO request);
    void logout(String authorization);
    List<DevUser> listDevUsers();
    LoginSession switchUser(SwitchUserReqVO request);
    MemberInfo loadMember(long userId, long companyId);
    MemberInfo loadMemberAnyCompany(long userId);
    List<CompanyRole> loadUserCompanies(long userId);
    CompanyProfile toCompanyProfile(CompanyDO company);
}
