#!/usr/bin/env python3
"""Generate explicit, reviewable HTTP adapters for the domain Java contracts.

Only method declarations from checked-in API/port interfaces are exported.
There is no reflective RPC endpoint, SQL payload, or runtime method lookup.
Run after changing an API and commit the generated Java source with it.
"""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
RPC = ROOT / 'tradepass-framework/tradepass-spring-boot-starter-rpc/src/main/java/com/tradepass/framework/rpc'
DEST = RPC / 'core'
DEST_CONFIG = RPC / 'config'
DEST.mkdir(parents=True, exist_ok=True)
DEST_CONFIG.mkdir(parents=True, exist_ok=True)

def parameters(value):
    parts, start, depth = [], 0, 0
    for i, char in enumerate(value):
        depth += (char == '<') - (char == '>')
        if char == ',' and depth == 0:
            parts.append(value[start:i].strip())
            start = i + 1
    if value[start:].strip():
        parts.append(value[start:].strip())
    return [p.rsplit(None, 1) for p in parts]

names = []
for role in ('identity', 'contract', 'trade', 'settlement'):
    api_root = ROOT / f'tradepass-module-{role}/tradepass-module-{role}-api/src/main/java'
    sources = sorted(api_root.rglob('*Operations.java'))
    sources += sorted(api_root.rglob('*Reader.java'))
    for path in sources:
        source = path.read_text()
        api = path.stem
        package = re.search(r'package ([\w.]+);', source)[1]
        imports = '\n'.join(re.findall(r'^import .+;', source, re.M))
        methods = re.findall(r'^    (?! )(?:public\s+)?(?!static\b|record\b|enum\b)([\w<>., ?\[\]]+?)\s+(\w+)\(([^()]*)\)\s*;', source, re.M)
        if not methods:
            raise ValueError(f'No explicit methods found: {path}')
        name = api + 'Http'
        names.append(name)
        lines = [f'''package com.tradepass.framework.rpc.core;

// Generated by scripts/generate-domain-rpc.py from {path.relative_to(ROOT)}.
{imports}
import {package}.{api};
import {package}.{api}.*;
import com.tradepass.framework.rpc.config.DomainFeignConfiguration;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.context.annotation.*;
import org.springframework.boot.autoconfigure.condition.*;
import org.springframework.web.bind.annotation.*;

@Configuration(proxyBeanMethods = false)
@ConditionalOnProperty(name = "tradepass.services.split", havingValue = "true")
@Import({name}.Endpoint.class)
public class {name} {{
''']
        entries = []
        for ret, method, args in methods:
            ps = parameters(args)
            key = method + str(len(ps))
            record = key[0].upper() + key[1:] + 'Request'
            lines.append(f'    public record {record}(' + ', '.join(t.replace('...', '[]') + ' ' + n for t, n in ps) + ') {}\n')
            entries.append((ret.strip(), method, key, record, ps))
        lines.append(f'''
    @FeignClient(name = "${{tradepass.services.{role}-name:tradepass-{role}}}", contextId = "{name}",
            url = "${{tradepass.services.{role}-url:}}", configuration = DomainFeignConfiguration.class)
    public interface Client {{
''')
        for ret, method, key, record, ps in entries:
            lines.append(f'        @PostMapping("/internal/domain/{api}/{key}")\n        {ret} {key}(@RequestBody {record} request);\n')
        lines.append(f'''    }}

    @Bean
    @ConditionalOnExpression("!T(com.tradepass.framework.common.core.HostedRoles).hosts('${{tradepass.runtime.role:}}', '{role}')")
    {api} remote{api}(Client client) {{
        return new {api}() {{
''')
        for ret, method, key, record, ps in entries:
            args = ', '.join(t + ' ' + n for t, n in ps)
            call = ', '.join(n for t, n in ps)
            prefix = '' if ret == 'void' else 'return '
            lines.append(f'            @Override public {ret} {method}({args}) {{ {prefix}client.{key}(new {record}({call})); }}\n')
        lines.append(f'''        }};
    }}

    @RestController
    @ConditionalOnExpression("T(com.tradepass.framework.common.core.HostedRoles).hosts('${{tradepass.runtime.role:}}', '{role}')")
    public static class Endpoint {{
        private final {api} operations;
        public Endpoint({api} operations) {{ this.operations = operations; }}
''')
        for ret, method, key, record, ps in entries:
            call = ', '.join('request.' + n + '()' for t, n in ps)
            prefix = '' if ret == 'void' else 'return '
            lines.append(f'        @PostMapping("/internal/domain/{api}/{key}")\n        public {ret} {key}(@RequestBody {record} request) {{ {prefix}operations.{method}({call}); }}\n')
        lines.append('    }\n}\n')
        (DEST / (name + '.java')).write_text(''.join(lines))

(DEST_CONFIG / 'DomainRpcConfiguration.java').write_text('''package com.tradepass.framework.rpc.config;

// Generated by scripts/generate-domain-rpc.py.
import com.tradepass.framework.rpc.core.*;
import org.springframework.context.annotation.*;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.cloud.openfeign.EnableFeignClients;

@Configuration(proxyBeanMethods = false)
@ConditionalOnProperty(name = "tradepass.services.split", havingValue = "true")
@Import({''' + ', '.join(n + '.class' for n in names) + '''})
@EnableFeignClients(clients = {''' + ', '.join(n + '.Client.class' for n in names) + '''})
public class DomainRpcConfiguration { }
''')
print(f'Generated {len(names)} typed domain adapters')
