#!/usr/bin/env python3
"""Rebuild the HTTP contract from controller mappings, including media constraints."""
from pathlib import Path
import json
import re

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'deploy/smoke-tests/src/test/resources/architecture/http-api-baseline.txt'
ROLES = ('identity', 'contract', 'trade', 'settlement', 'file')
MEDIA = {'APPLICATION_JSON_VALUE': 'application/json', 'APPLICATION_PDF_VALUE': 'application/pdf',
         'MULTIPART_FORM_DATA_VALUE': 'multipart/form-data',
         'APPLICATION_FORM_URLENCODED_VALUE': 'application/x-www-form-urlencoded',
         'APPLICATION_OCTET_STREAM_VALUE': 'application/octet-stream'}
STRING = r'"(?:\\.|[^"\\])*"'


def path_value(args):
    match = re.search(r'(?:^\s*|\b(?:value|path)\s*=\s*)(' + STRING + ')', args)
    return json.loads(match[1]) if match else ''


def media_value(args, key):
    match = re.search(r'\b' + key + r'\s*=\s*(MediaType\.(\w+)|' + STRING + ')', args)
    if not match:
        if re.search(r'\b' + key + r'\s*=', args):
            raise ValueError('Unsupported mapping media expression: ' + args)
        return ''
    return MEDIA[match[2]] if match[2] else json.loads(match[1])


def collect_source(source):
    class_mapping = re.search(r'@RequestMapping\s*\(([^)]*)\)', source)
    args = class_mapping[1] if class_mapping else ''
    prefix = path_value(args).rstrip('/')
    entries = []
    for match in re.finditer(r'@(Get|Post|Put|Delete|Patch)Mapping\b(?:[ \t]*\(([^)]*)\))?', source):
        method_args = match[2] or ''
        suffix = path_value(method_args)
        path = prefix + ('/' + suffix.lstrip('/') if suffix else '')
        clause = '{' + match[1].upper() + ' [' + (path or '/') + ']'
        for key in ('consumes', 'produces'):
            value = media_value(method_args, key) or media_value(args, key)
            if value:
                clause += ', ' + key + ' [' + value + ']'
        entries.append(clause + '}')
    return entries


def collect():
    entries = set()
    for role in ROLES:
        base = ROOT / f'tradepass-module-{role}/tradepass-module-{role}-server/src/main/java'
        for path in base.rglob('*Controller.java'):
            if '/controller/app/' in str(path):
                entries.update(collect_source(path.read_text()))
    probe = ROOT / 'tradepass-framework/tradepass-spring-boot-starter-web/src/main/java/com/tradepass/framework/web/core/controller/ProbeController.java'
    entries.update(collect_source(probe.read_text()))
    return sorted(entries)


def main():
    lines = collect()
    OUT.write_text('# Generated by scripts/generate-http-api-baseline.py\n' + '\n'.join(lines) + '\n')
    print(f'Wrote {len(lines)} mappings to {OUT}')


if __name__ == '__main__':
    main()
