server {

    listen 443 ssl;

    server_name jenkins.sqt.org.cn;


    server_tokens off;


    ssl_certificate /etc/nginx/tls/fullchain.pem;

    ssl_certificate_key /etc/nginx/tls/privkey.pem;


    location / {


        proxy_pass http://127.0.0.1:18080;


        proxy_http_version 1.1;


        proxy_set_header Host $host;

        proxy_set_header X-Real-IP $remote_addr;

        proxy_set_header X-Forwarded-For $remote_addr;

        proxy_set_header X-Forwarded-Proto https;


        proxy_set_header Upgrade $http_upgrade;

        proxy_set_header Connection "upgrade";


        proxy_read_timeout 300s;
    }
}
