package com.tradepass.module.identity.service.company;

import com.tradepass.framework.common.pojo.TradePassDtos;
import com.tradepass.module.identity.service.fadada.FadadaPersonalIdentityService;
import com.tradepass.module.identity.service.notice.MemberRemovalNoticeService;
import com.tradepass.module.identity.service.permission.AccessControlService;
import com.tradepass.module.identity.service.permission.RolePermissionService;
import com.tradepass.framework.audit.core.AuditLogService;
import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.baomidou.mybatisplus.core.conditions.update.LambdaUpdateWrapper;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.core.type.TypeReference;
import com.tradepass.framework.common.core.AuthContext;
import com.tradepass.framework.common.exception.BusinessException;
import com.tradepass.framework.common.pojo.TradePassDtos.AuthorizationRecord;
import com.tradepass.framework.common.pojo.TradePassDtos.MemberRole;
import com.tradepass.framework.common.pojo.TradePassDtos.CompanyProfile;
import com.tradepass.framework.common.pojo.TradePassDtos.CompanySearchSummary;
import com.tradepass.framework.common.pojo.TradePassDtos.SealRecord;
import com.tradepass.module.identity.controller.app.company.vo.ApproveReqVO;
import com.tradepass.module.identity.controller.app.company.vo.CompanySubmitReqVO;
import com.tradepass.module.identity.controller.app.company.vo.InviteReqVO;
import com.tradepass.module.identity.controller.app.company.vo.JoinReqVO;
import com.tradepass.module.identity.controller.app.company.vo.RoleReqVO;
import com.tradepass.module.identity.controller.app.company.vo.SealReqVO;
import com.tradepass.module.identity.controller.app.company.vo.VerificationReqVO;
import com.tradepass.module.identity.api.company.dto.InviteResult;
import com.tradepass.module.identity.api.company.dto.JoinResult;
import com.tradepass.framework.common.pojo.PagePayload;
import com.tradepass.module.identity.api.permission.dto.RoleRespDTO;
import com.tradepass.module.identity.dal.dataobject.company.CompanyDO;
import com.tradepass.module.identity.dal.dataobject.company.CompanyInviteDO;
import com.tradepass.module.identity.dal.dataobject.company.CompanyMemberDO;
import com.tradepass.module.identity.api.fadada.dto.PersonalIdentityRespDTO;
import com.tradepass.module.identity.dal.dataobject.counterparty.CounterpartyRelationEntityDO;
import com.tradepass.module.identity.dal.dataobject.permission.RoleDefDO;
import com.tradepass.module.identity.dal.mysql.company.CompanyInviteMapper;
import com.tradepass.module.identity.dal.mysql.company.CompanyMapper;
import com.tradepass.module.identity.dal.mysql.company.CompanyMemberMapper;
import com.tradepass.module.identity.dal.mysql.counterparty.CounterpartyRelationMapper;
import com.tradepass.module.identity.dal.mysql.permission.PermDefMapper;
import com.tradepass.module.identity.dal.mysql.permission.RoleDefMapper;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.beans.factory.annotation.Autowired;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;
import java.util.LinkedHashSet;
import java.util.Set;
import java.util.UUID;

public interface CompanyService {
    void setPersonalIdentityService(FadadaPersonalIdentityService personalIdentityService);
    List<CompanySearchSummary> searchCompanies(String keyword);
    CompanyProfile getCompany(String id);
    List<CompanyProfile> myOnboardingCompanies();
    CompanyProfile submitCompany(CompanySubmitReqVO request);
    CompanyProfile submitCertification(String id);
    CompanyProfile verifyRealName(VerificationReqVO req);
    CompanyProfile verifyFace(VerificationReqVO req);
    SealRecord uploadSeal(SealReqVO req);
    boolean caMockEnabled();
    InviteResult createInvite(InviteReqVO req);
    InviteResult createCounterpartyInvite(InviteReqVO req);
    JoinResult joinCompany(JoinReqVO req);
    List<AuthorizationRecord> listMembers(String companyId);
    PagePayload<AuthorizationRecord> pageMembers(String companyId, String status, int page, int size);
    AuthorizationRecord approveMember(String id, ApproveReqVO req, String companyId);
    void rejectMember(String id, String companyId);
    void updateMemberRole(String id, ApproveReqVO req, String companyId);
    void removeMember(String id, String companyId);
    List<RoleRespDTO> listRoles(String companyId);
    RoleRespDTO createRole(RoleReqVO req);
    void updateRole(String id, RoleReqVO req);
    void deleteRole(String id);
}
