-- Preserve existing IDs and foreign keys; all new business IDs are supplied by the application.
-- MySQL requires disabling FK checks while removing AUTO_INCREMENT from referenced keys.
SET @tradepass_previous_fk_checks = @@FOREIGN_KEY_CHECKS;
SET FOREIGN_KEY_CHECKS = 0;
ALTER TABLE `approval_result_notification` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `audit_log` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `bilateral_action_request` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `business_document` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `business_document_item` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `business_document_template` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `business_memo` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `company` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `company_certification_application` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `company_invite` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `company_member` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `contract_archive` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `contract_attachment` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `contract_template` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `counterparty_relation` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `fadada_callback_event` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `fadada_contract_sign_task` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `fadada_corp_identity` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `fadada_corp_seal` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `fadada_user_identity` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `inventory_balance` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `inventory_inbound` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `inventory_inbound_item` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `inventory_product` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `inventory_transaction` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `inventory_transfer` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `logistics_document` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `project_contract_assignment` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `project_contract_prompt_preference` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `project_ledger` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `reconciliation_entry` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `reconciliation_statement` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `role_def` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `sales_order_receipt` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `sys_user` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `template_category` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `trade_contract` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `trade_order` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `warehouse` MODIFY COLUMN `id` BIGINT NOT NULL;
SET FOREIGN_KEY_CHECKS = @tradepass_previous_fk_checks;
